CODE_OF_CONDUCT.md

Adds a Code of Conduct which is in line with the [Contributor Covenant](http://contributor-covenant.org)

feat(Code of Conduct) - Adds Code of Conduct

---

Rx.NET/Source/System.Reactive.Core/Reactive/ObserverBase.cs

Should fix #143 
/cc @bartdesmet

Add Volatile Read/Write around isStopped for thread safety

---

Ix.NET/Source/System.Interactive.Async/AsyncEnumerable.Creation.cs

Made Ix-Async factory methods public

---

Ix.NET/Source/Tests/AsyncTests.Bugs.cs

CanCancel test fix

---

NuGet.Config
Rx.NET/Source/Microsoft.Reactive.Testing/project.json
Rx.NET/Source/NuSpecs/Microsoft.Reactive.Testing.nuspec

Remove xUnit dependency by internalizing assert source

---

README.md

Just in case I'm not the only one that was confused as I was in #242: link to nuget package page from package name.

Include links to nuget

---

Ix.NET/Source/NuSpecs/System.Interactive.Async.nuspec
Ix.NET/Source/NuSpecs/System.Interactive.nuspec
Ix.NET/Source/System.Interactive.Async/project.json
Ix.NET/Source/System.Interactive/project.json
Ix.NET/Source/global.json
Rx.NET/Source/NuSpecs/System.Reactive.Interfaces.nuspec
Rx.NET/Source/System.Reactive.Interfaces/project.json
Rx.NET/Source/global.json

Hotfix to reduce dependencies for net45

---

Rx.NET/Source/src/System.Reactive/Concurrency/TaskHelpers.cs
Rx.NET/Source/src/System.Reactive/Concurrency/TaskPoolScheduler.cs
Rx.NET/Source/tests/Tests.System.Reactive/Stress/Linq/ReplaySubject.cs

Removing conditional compilation checks for `Task.Delay`.

Task.Delay exists on all platforms now

---

Rx.NET/Source/tests/Tests.System.Reactive/Tests/Concurrency/SynchronizationTest.cs
Rx.NET/Source/tests/Tests.System.Reactive/Tests/Linq/ObservableConcurrencyTest.cs
Rx.NET/Source/tests/Tests.System.Reactive/Tests/ObserverTest.cs

Removing a few symbols in test code that are no longer in use.

Removing a few conditional compilation symbols

---

Rx.NET/Source/src/System.Reactive/Threading/Tasks/TaskObservableExtensions.cs

Misc. improvements to `TaskObservableExtensions`.

Cleanup of TaskObservableExtensions

---

Rx.NET/Source/src/System.Reactive/EventPatternSourceBase.cs
Rx.NET/Source/src/System.Reactive/EventSource.cs

Noticed some unnecessary lambda abstraction; removing it.

Eta reduction of some lambdas

---

Rx.NET/Source/src/System.Reactive/Linq/Observable.Aggregates.cs
Rx.NET/Source/src/System.Reactive/Linq/Qbservable.Generated.cs

Addressing some issues with warnings caused by XML docs.

Fixing XML doc comments

---

Rx.NET/Source/src/System.Reactive/Disposables/CancellationDisposable.cs
Rx.NET/Source/src/System.Reactive/Disposables/CompositeDisposable.cs
Rx.NET/Source/src/System.Reactive/Disposables/MultipleAssignmentDisposable.cs
Rx.NET/Source/src/System.Reactive/Disposables/RefCountDisposable.cs
Rx.NET/Source/src/System.Reactive/Disposables/ScheduledDisposable.cs
Rx.NET/Source/src/System.Reactive/Disposables/SerialDisposable.cs
Rx.NET/Source/src/System.Reactive/Disposables/SingleAssignmentDisposable.cs
Rx.NET/Source/src/System.Reactive/Disposables/StableCompositeDisposable.cs

Some imrpovements to the disposable types using C# 6.0 and stylistic improvements.

Misc. improvements to Disposable types

---

Ix.NET/Source/Directory.build.props

This is the "supported" property, just a tweak to clean up a bit.
cc @onovotny

Update .props to use $(NuGetPackageRoot)

---

Rx.NET/Source/src/System.Reactive.Interfaces/version.json

pin interfaces to 4.0

---

Rx.NET/Source/src/System.Reactive/Concurrency/DefaultScheduler.cs
Rx.NET/Source/src/System.Reactive/Concurrency/Synchronization.cs
Rx.NET/Source/src/System.Reactive/Concurrency/TaskPoolScheduler.cs

Again in the Concurrency namespace.

Save even more allocations

---

Ix.NET/Source/System.Interactive.Async.Providers/AsyncEnumerableRewriter.cs
Ix.NET/Source/System.Interactive.Async.Tests/AsyncTests.Aggregates.cs
Ix.NET/Source/System.Interactive.Async.Tests/AsyncTests.Bugs.cs
Ix.NET/Source/System.Interactive.Async.Tests/AsyncTests.Conversions.cs
Ix.NET/Source/System.Interactive.Async.Tests/AsyncTests.Creation.cs
Ix.NET/Source/System.Interactive.Async.Tests/AsyncTests.Multiple.cs
Ix.NET/Source/System.Interactive.Async.Tests/AsyncTests.Single.cs
Ix.NET/Source/System.Interactive.Async/Concatenate.cs
Ix.NET/Source/System.Interactive.Async/ToObservable.cs
Ix.NET/Source/System.Interactive.Tests/Tests.Buffering.cs
Ix.NET/Source/System.Interactive.Tests/Tests.Qbservable.cs
Ix.NET/Source/System.Interactive.Tests/Tests.Single.cs

Fix xUnit warnings and apply code style fixes to match editorconfig

---

Rx.NET/Source/src/System.Reactive/Linq/Observable/ToLookup.cs

Release the lookup reference if there is a failure or completion.

4.x: ToLookup() release lookup upon failure/termination

---

Rx.NET/Source/src/System.Reactive/Linq/Observable/ToList.cs

Release the list field upon failure or completion.

4.x: ToList() release reference to the list upon termination

---

.gitignore
Ix.NET/Source/Directory.build.props
Ix.NET/Source/Directory.build.targets
Ix.NET/Source/Ix.NET.sln
Ix.NET/Source/System.Interactive.Async.Providers/Properties/AssemblyInfo.cs
Ix.NET/Source/System.Interactive.Async/Properties/AssemblyInfo.cs
Ix.NET/Source/System.Interactive.Providers/Properties/AssemblyInfo.cs
Ix.NET/Source/System.Interactive.Providers/QueryableEx.cs
Ix.NET/Source/System.Interactive.Providers/System.Interactive.Providers.csproj
Ix.NET/Source/System.Interactive.Providers/System.Interactive.Providers.v3.ncrunchproject
Ix.NET/Source/System.Interactive/Properties/AssemblyInfo.cs
Ix.NET/Source/System.Interactive/Skip.cs
Ix.NET/Source/System.Interactive/System.Interactive.csproj
Ix.NET/Source/System.Interactive/Take.cs
Ix.NET/Source/refs/Directory.build.props
Ix.NET/Source/refs/System.Interactive.Providers/System.Interactive.Providers.csproj
Ix.NET/Source/refs/System.Interactive/System.Interactive.csproj

Fixes #735 
Adds refs for Providers

Ix Providers refs

---

Ix.NET/Source/System.Interactive.Async/Catch.cs
Ix.NET/Source/System.Interactive.Async/Create.cs
Ix.NET/Source/System.Interactive.Async/Set.cs
Ix.NET/Source/System.Interactive.Providers/QueryableEx.cs
Ix.NET/Source/System.Interactive/Repeat.cs
Ix.NET/Source/System.Interactive/SelectMany.cs

Fix some misspellings in Ix docs/comments.

Ix: Fix some misspellings

---

Ix.NET/Source/Benchmarks.System.Interactive/Program.cs
Ix.NET/Source/Benchmarks.System.Interactive/RetryBenchmark.cs
Ix.NET/Source/System.Interactive/Retry.cs

This PR reimplements the Ix `Retry()` operators (infinite, max count) directly.
(The comparison benchmark will be added next morning.)

Ix: Implement the Retry() operator directly

---

Ix.NET/Source/Benchmarks.System.Interactive/Program.cs
Ix.NET/Source/System.Interactive/Defer.cs

Fix some of the warnings and remove commented out code.

Ix: some cleanups from recent PRs

---

Rx.NET/Source/src/System.Reactive/Linq/Observable/RefCount.cs
Rx.NET/Source/tests/Tests.System.Reactive/Tests/Linq/Observable/RefCountTest.cs

Revert changes to RefCount from 6ecc899a4ba35db5834f55dcfde019e19b431940.
We might take another attempt to optimize it.
Fixes #768.

Revert changes to RefCount.

---

Rx.NET/Source/tests/Tests.System.Reactive/Tests/Concurrency/VirtualSchedulerTest.cs

See #785. I ran all test 10 times without any failure.

No false positives for the Virtual_ThreadSafety test.

---

Ix.NET/Source/System.Interactive/System/Linq/Operators/Share.cs

Apply the Ix `Share` fix from #627 onto the IxAsyncCSharp8 branch.

IxCS8: Allow Share to be disposed

---

Rx.NET/Source/facades/System.Reactive.Compatibility.nuspec

was stopping the build - https://dev.azure.com/dotnet/Rx.NET/_build/results?buildId=5813&view=logs

fix packageUrl property

---

Ix.NET/Source/System.Interactive.Async/System/Linq/Operators/Catch.cs
Ix.NET/Source/System.Interactive.Async/System/Linq/Operators/DistinctUntilChanged.cs
Ix.NET/Source/System.Interactive.Async/System/Linq/Operators/Do.cs
Ix.NET/Source/System.Interactive.Async/System/Linq/Operators/IsEmpty.cs
Ix.NET/Source/System.Interactive.Async/System/Linq/Operators/Max.cs
Ix.NET/Source/System.Interactive.Async/System/Linq/Operators/Min.cs
Ix.NET/Source/System.Interactive.Async/System/Linq/Operators/Scan.cs
Ix.NET/Source/System.Interactive.Async/System/Linq/Operators/Timeout.cs
Ix.NET/Source/System.Interactive.Async/System/Linq/Operators/Using.cs
Ix.NET/Source/System.Linq.Async/System/Linq/AsyncEnumerableHelpers.cs
Ix.NET/Source/System.Linq.Async/System/Linq/Operators/Aggregate.cs
Ix.NET/Source/System.Linq.Async/System/Linq/Operators/Any.cs
Ix.NET/Source/System.Linq.Async/System/Linq/Operators/AppendPrepend.cs
Ix.NET/Source/System.Linq.Async/System/Linq/Operators/GroupJoin.cs
Ix.NET/Source/System.Linq.Async/System/Linq/Operators/Join.cs
Ix.NET/Source/System.Linq.Async/System/Linq/Operators/OrderedAsyncEnumerable.cs
Ix.NET/Source/System.Linq.Async/System/Linq/Operators/SequenceEqual.cs
Ix.NET/Source/System.Linq.Async/System/Linq/Operators/Single.cs
Ix.NET/Source/System.Linq.Async/System/Linq/Operators/SkipLast.cs
Ix.NET/Source/System.Linq.Async/System/Linq/Operators/SkipWhile.cs
Ix.NET/Source/System.Linq.Async/System/Linq/Operators/Zip.cs

Simplify some code a bit more using C# 8.0 features.

Use using declarations

---

Ix.NET/Source/System.Interactive/System/Linq/Operators/Catch.cs
Ix.NET/Source/System.Interactive/System/Linq/Operators/Concat.cs
Ix.NET/Source/System.Interactive/System/Linq/Operators/Create.cs
Ix.NET/Source/System.Interactive/System/Linq/Operators/Do.cs
Ix.NET/Source/System.Interactive/System/Linq/Operators/Expand.cs
Ix.NET/Source/System.Interactive/System/Linq/Operators/Finally.cs
Ix.NET/Source/System.Interactive/System/Linq/Operators/For.cs
Ix.NET/Source/System.Interactive/System/Linq/Operators/ForEach.cs
Ix.NET/Source/System.Interactive/System/Linq/Operators/Generate.cs
Ix.NET/Source/System.Interactive/System/Linq/Operators/Hide.cs
Ix.NET/Source/System.Interactive/System/Linq/Operators/If.cs
Ix.NET/Source/System.Interactive/System/Linq/Operators/IsEmpty.cs
Ix.NET/Source/System.Interactive/System/Linq/Operators/OnErrorResumeNext.cs
Ix.NET/Source/System.Interactive/System/Linq/Operators/Publish.cs
Ix.NET/Source/System.Interactive/System/Linq/Operators/Repeat.cs
Ix.NET/Source/System.Interactive/System/Linq/Operators/Scan.cs
Ix.NET/Source/System.Interactive/System/Linq/Operators/SelectMany.cs
Ix.NET/Source/System.Interactive/System/Linq/Operators/Share.cs
Ix.NET/Source/System.Interactive/System/Linq/Operators/SkipLast.cs
Ix.NET/Source/System.Interactive/System/Linq/Operators/StartsWith.cs
Ix.NET/Source/System.Interactive/System/Linq/Operators/TakeLast.cs
Ix.NET/Source/System.Interactive/System/Linq/Operators/Throw.cs
Ix.NET/Source/System.Interactive/System/Linq/Operators/Using.cs
Ix.NET/Source/System.Interactive/System/Linq/Operators/While.cs
Ix.NET/Source/System.Interactive/System/Linq/RefCountList.cs
Ix.NET/Source/System.Interactive/System/Linq/Yielder.cs

Use newer C# features where appropriate.

Modernize some Ix code

---

Rx.NET/Source/benchmarks/Benchmarks.System.Reactive/Benchmarks.System.Reactive.csproj

Revert "Bump System.Reactive from 3.1.1 to 4.1.5 in /Rx.NET/Source"

---

README.md

Added few more links to various docs to the main README file.

Added docs sources

---

Ix.NET/Source/Benchmarks.System.Interactive/Program.cs
Ix.NET/Source/System.Interactive.Async.Providers.Tests/AssertEx.cs
Ix.NET/Source/System.Interactive.Async.Tests/System/Linq/Operators/Never.cs
Ix.NET/Source/System.Interactive.Tests/AssertEx.cs
Ix.NET/Source/System.Interactive.Tests/System/Linq/Operators/Publish.cs
Ix.NET/Source/System.Interactive/System/Linq/Operators/IgnoreElements.cs
Ix.NET/Source/System.Linq.Async.Queryable.Tests/AssertEx.cs
Ix.NET/Source/System.Linq.Async.Tests/System/Linq/Operators/ToAsyncEnumerable.cs
Ix.NET/Source/System.Linq.Async.Tests/System/Linq/Operators/ToObservable.cs

Misc. minor things reported as IDE warnings. Mostly for test code.

Address a few minor IDE warnings

---

Rx.NET/Source/src/System.Reactive/Concurrency/CatchScheduler.cs

This time in CatchSchedulerLongRunning. See #1116
**I have not built or tested this at all because I literally couldn't figure out how to (I'm on Linux), but I hope it works/is helpful.**

Fix another case of infinite generics recursion.

---

Rx.NET/Source/src/Microsoft.Reactive.Testing/ReactiveAssert.cs
Rx.NET/Source/tests/Tests.System.Reactive.ApiApprovals/Api/ApiApprovalTests.Testing.verified.cs

Support for https://github.com/dotnet/reactive/issues/1191.

Add EqualityComparer<T> support in ReactiveAssert.

---

Rx.NET/Source/src/System.Reactive/Internal/Helpers.cs
Rx.NET/Source/src/System.Reactive/Internal/Lookup.cs
Rx.NET/Source/src/System.Reactive/Internal/PlatformEnlightenmentProvider.cs
Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs
Rx.NET/Source/src/System.Reactive/Internal/Sink.cs
Rx.NET/Source/src/System.Reactive/Internal/StopwatchImpl.cs
Rx.NET/Source/src/System.Reactive/Internal/TailRecursiveSink.cs
Rx.NET/Source/src/System.Reactive/ListObservable.cs
Rx.NET/Source/src/System.Reactive/Notification.cs
Rx.NET/Source/src/System.Reactive/Runtime/CompilerServices/TaskObservableMethodBuilder.cs
Rx.NET/Source/src/System.Reactive/Threading/Tasks/TaskObservableExtensions.cs

Some trivial changes leveraging newer C# features. Ensuring tool chain is set up correctly in CI as well.

Modernize some code

---

AsyncRx.NET/System.Reactive.Async.Concurrency/System/Reactive/Concurrency/AsyncScheduler.cs
AsyncRx.NET/System.Reactive.Async.Concurrency/System/Reactive/Concurrency/SynchronizationContextAsyncScheduler.cs
AsyncRx.NET/System.Reactive.Async.Concurrency/System/Reactive/Concurrency/TaskPoolAsyncScheduler.cs
AsyncRx.NET/System.Reactive.Async.Core/System/Reactive/AsyncObservable.cs
AsyncRx.NET/System.Reactive.Async.Core/System/Reactive/AsyncObserver.cs
AsyncRx.NET/System.Reactive.Async.Disposables/System/Reactive/Disposables/AsyncDisposable.cs
AsyncRx.NET/System.Reactive.Async.Disposables/System/Reactive/Disposables/CancellationAsyncDisposable.cs
AsyncRx.NET/System.Reactive.Async.Disposables/System/Reactive/Disposables/RefCountAsyncDisposable.cs
AsyncRx.NET/System.Reactive.Async.Linq/System/Runtime/CompilerServices/AsyncObservableMethodBuilder.cs
AsyncRx.NET/System.Reactive.Async.Subjects/System/Reactive/Subjects/ReplayAsyncSubject.cs
AsyncRx.NET/System.Reactive.Bcl/System/Threading/AsyncLock.cs

A few more small improvements.

Misc. code improvements.

---

AsyncRx.NET/System.Reactive.Async.Concurrency/System/Reactive/Concurrency/AsyncScheduler.cs
AsyncRx.NET/System.Reactive.Async.Core/System/Reactive/AsyncObservableBase.cs

Some more cleanup and adding a missing `ConfigureAwait(false)`.

Simplify some code

---

Ix.NET/Source/System.Linq.Async.Queryable/System.Linq.Async.Queryable.csproj
Ix.NET/Source/System.Linq.Async/System.Linq.Async.csproj

Addresses https://github.com/dotnet/reactive/issues/873.

Add package descriptions for System.Linq.Async etc.

---

Rx.NET/Source/src/Microsoft.Reactive.Testing/ReactiveAssert.cs
Rx.NET/Source/src/System.Reactive/Concurrency/EventLoopScheduler.cs
Rx.NET/Source/src/System.Reactive/Linq/QueryLanguage.Creation.cs
Rx.NET/Source/src/System.Reactive/Platforms/UWP/Concurrency/CoreDispatcherScheduler.cs
Rx.NET/Source/src/System.Reactive/Subjects/AsyncSubject.cs

Take care of a few easy warnings.

Address a few warnings.

---

Rx.NET/Source/src/System.Reactive/Linq/QueryLanguage.Blocking.cs
Rx.NET/Source/src/System.Reactive/Notification.cs
Rx.NET/Source/src/System.Reactive/ObservableQuery.cs

Harvest a couple more `#if` checks that are constants and hence redundant.

Remove more #if checks.

---

Rx.NET/Source/src/Microsoft.Reactive.Testing/Recorded.cs
Rx.NET/Source/src/Microsoft.Reactive.Testing/Subscription.cs
Rx.NET/Source/src/System.Reactive/Concurrency/ScheduledItem.cs
Rx.NET/Source/src/System.Reactive/TimeInterval.cs
Rx.NET/Source/src/System.Reactive/Timestamped.cs

Clean up a few things and leave remarks to improve `GetHashCode` for some types. There's potential for optimization of `ToString` as well.

Modernize some code.

---

Rx.NET/Source/src/System.Reactive/Concurrency/TaskHelpers.cs
Rx.NET/Source/src/System.Reactive/Linq/Observable/Throw.cs
Rx.NET/Source/src/System.Reactive/Threading/Tasks/TaskObservableExtensions.cs
Rx.NET/Source/tests/Tests.System.Reactive.ApiApprovals/Api/ApiApprovalTests.Core.verified.cs

Enable C# 8.0 nullable in two more files.

Nullable for TaskObservableExtensions.

---

Rx.NET/Source/src/System.Reactive/AnonymousSafeObserver.cs
Rx.NET/Source/src/System.Reactive/Concurrency/TaskHelpers.cs
Rx.NET/Source/src/System.Reactive/EventPattern.cs
Rx.NET/Source/src/System.Reactive/EventPatternSource.cs
Rx.NET/Source/src/System.Reactive/EventPatternSourceBase.cs
Rx.NET/Source/src/System.Reactive/EventSource.cs
Rx.NET/Source/src/System.Reactive/ListObservable.cs
Rx.NET/Source/src/System.Reactive/Notification.cs
Rx.NET/Source/src/System.Reactive/Observable.Extensions.cs
Rx.NET/Source/src/System.Reactive/ObservableQuery.cs
Rx.NET/Source/src/System.Reactive/Runtime/CompilerServices/TaskObservableMethodBuilder.cs
Rx.NET/Source/src/System.Reactive/TaskObservable.cs
Rx.NET/Source/src/System.Reactive/TimeInterval.cs
Rx.NET/Source/src/System.Reactive/Timestamped.cs
Rx.NET/Source/src/System.Reactive/Unit.cs
Rx.NET/Source/tests/Tests.System.Reactive.ApiApprovals/Api/ApiApprovalTests.Core.verified.cs

Mostly on the root folder with essential types that are used across the board.
Progress to 0 suppressions: `249/337` left

Another batch of #nullable enable.

---

Rx.NET/Source/src/System.Reactive/Concurrency/CurrentThreadScheduler.cs
Rx.NET/Source/src/System.Reactive/Concurrency/IScheduler.cs
Rx.NET/Source/src/System.Reactive/Concurrency/ISchedulerLongRunning.cs
Rx.NET/Source/src/System.Reactive/Concurrency/ISchedulerPeriodic.cs
Rx.NET/Source/src/System.Reactive/Concurrency/ImmediateScheduler.cs
Rx.NET/Source/src/System.Reactive/Concurrency/LocalScheduler.TimerQueue.cs
Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Wrappers.cs
Rx.NET/Source/src/System.Reactive/Concurrency/SchedulerDefaults.cs
Rx.NET/Source/src/System.Reactive/Concurrency/SchedulerOperation.cs
Rx.NET/Source/src/System.Reactive/Concurrency/SchedulerQueue.cs
Rx.NET/Source/src/System.Reactive/Disposables/BooleanDisposable.cs
Rx.NET/Source/src/System.Reactive/Linq/Observable/Empty.cs
Rx.NET/Source/src/System.Reactive/Linq/Observable/Never.cs
Rx.NET/Source/src/System.Reactive/Linq/Observable/Return.cs
Rx.NET/Source/src/System.Reactive/Subjects/ConnectableObservable.cs
Rx.NET/Source/src/System.Reactive/Subjects/Subject.Extensions.cs
Rx.NET/Source/src/System.Reactive/Subjects/SubjectBase.cs

Some more simple changes.
Progress to 0 suppressions: `209/337` left

Harvest some low-hanging nullable fruit.

---

Rx.NET/Source/src/System.Reactive/Concurrency/CatchScheduler.cs
Rx.NET/Source/src/System.Reactive/Concurrency/DefaultScheduler.cs
Rx.NET/Source/src/System.Reactive/Concurrency/DisableOptimizationsScheduler.cs
Rx.NET/Source/src/System.Reactive/Concurrency/EventLoopScheduler.cs
Rx.NET/Source/src/System.Reactive/Concurrency/HistoricalScheduler.cs
Rx.NET/Source/src/System.Reactive/Concurrency/LocalScheduler.cs
Rx.NET/Source/src/System.Reactive/Concurrency/NewThreadScheduler.cs
Rx.NET/Source/src/System.Reactive/Concurrency/ScheduledItem.cs
Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Async.cs
Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Recursive.cs
Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Services.Emulation.cs
Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Services.cs
Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs
Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.cs
Rx.NET/Source/src/System.Reactive/Concurrency/SchedulerWrapper.cs
Rx.NET/Source/src/System.Reactive/Concurrency/SynchronizationContextScheduler.cs
Rx.NET/Source/src/System.Reactive/Concurrency/TaskPoolScheduler.cs
Rx.NET/Source/src/System.Reactive/Concurrency/UserWorkItem.cs
Rx.NET/Source/src/System.Reactive/Concurrency/VirtualTimeScheduler.cs
Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs
Rx.NET/Source/src/System.Reactive/System.Reactive.csproj
Rx.NET/Source/src/System.Reactive/Threading/Tasks/TaskObservableExtensions.cs
Rx.NET/Source/tests/Tests.System.Reactive.ApiApprovals/Api/ApiApprovalTests.Core.verified.cs

Another piece of the #nullable` puzzle, tackling a significant portion of scheduler code.
Progress to 0 suppressions: `88/337` left

Enable #nullable in scheduler code.

---

Rx.NET/Source/src/System.Reactive/Concurrency/ConcurrencyAbstractionLayer.cs
Rx.NET/Source/src/System.Reactive/Concurrency/ConcurrencyAbstractionLayerImpl.Windows.cs
Rx.NET/Source/src/System.Reactive/Concurrency/ConcurrencyAbstractionLayerImpl.cs
Rx.NET/Source/src/System.Reactive/Concurrency/Synchronization.ObserveOn.cs
Rx.NET/Source/src/System.Reactive/Concurrency/Synchronization.cs
Rx.NET/Source/src/System.Reactive/Concurrency/ThreadPoolScheduler.Windows.cs
Rx.NET/Source/src/System.Reactive/Concurrency/ThreadPoolScheduler.cs
Rx.NET/Source/src/System.Reactive/Concurrency/VirtualTimeScheduler.Extensions.cs

Remaining pieces of scheduler code to be made `#nullable` aware.
Progress to 0 suppressions: `80/337` left

More #nullable for scheduler code.

---

Rx.NET/Source/src/System.Reactive/Internal/PlatformEnlightenmentProvider.cs
Rx.NET/Source/tests/Tests.System.Reactive.ApiApprovals/Api/ApiApprovalTests.Core.verified.cs

Keep some stuff around

---

Rx.NET/Source/src/System.Reactive/Concurrency/ConcurrencyAbstractionLayer.cs
Rx.NET/Source/src/System.Reactive/Concurrency/ConcurrencyAbstractionLayerImpl.Windows.cs
Rx.NET/Source/src/System.Reactive/Concurrency/ConcurrencyAbstractionLayerImpl.cs
Rx.NET/Source/src/System.Reactive/Concurrency/DefaultScheduler.cs
Rx.NET/Source/src/System.Reactive/Concurrency/EventLoopScheduler.cs
Rx.NET/Source/src/System.Reactive/Concurrency/UserWorkItem.cs
Rx.NET/Source/tests/Tests.System.Reactive.ApiApprovals/Api/ApiApprovalTests.Core.verified.cs

Match signatures of BCL functionality that the CAL abstracts over.

Fix some #nullable in the CAL.

---

Rx.NET/Source/src/System.Reactive/Platforms/Desktop/Concurrency/ControlScheduler.cs
Rx.NET/Source/src/System.Reactive/Platforms/Desktop/Concurrency/DispatcherScheduler.cs
Rx.NET/Source/src/System.Reactive/Platforms/UWP/Concurrency/CoreDispatcherScheduler.cs

More trivial changes to enable `#nullable` across the board.
Progress to 0 suppressions: `76/337` left

Enable #nullable for a few more scheduler types.

---

Rx.NET/Source/src/System.Reactive/Internal/TailRecursiveSink.cs
Rx.NET/Source/src/System.Reactive/Linq/Observable/Skip.cs
Rx.NET/Source/src/System.Reactive/Linq/Observable/SkipLast.cs
Rx.NET/Source/src/System.Reactive/Linq/Observable/SkipWhile.cs
Rx.NET/Source/src/System.Reactive/Linq/Observable/Take.cs
Rx.NET/Source/src/System.Reactive/Linq/Observable/TakeLast.cs
Rx.NET/Source/src/System.Reactive/Linq/Observable/TakeLastBuffer.cs
Rx.NET/Source/src/System.Reactive/Linq/Observable/TakeWhile.cs
Rx.NET/Source/src/System.Reactive/Linq/Observable/ToObservable.cs

More #nullable for operator implementations.

---

Rx.NET/Source/src/System.Reactive/Linq/Observable/Amb.cs
Rx.NET/Source/src/System.Reactive/Linq/Observable/AmbMany.cs
Rx.NET/Source/src/System.Reactive/Linq/Observable/Case.cs
Rx.NET/Source/src/System.Reactive/Linq/Observable/Catch.cs
Rx.NET/Source/src/System.Reactive/Linq/Observable/Concat.cs
Rx.NET/Source/src/System.Reactive/Linq/Observable/ConcatMany.cs
Rx.NET/Source/src/System.Reactive/Linq/Observable/SequenceEqual.cs
Rx.NET/Source/src/System.Reactive/Linq/Observable/WithLatestFrom.cs

Progress to 0 suppressions: `50/337` left

Enable #nullable for some straightforward operators.

---

Rx.NET/Source/src/System.Reactive/EventPattern.cs
Rx.NET/Source/src/System.Reactive/EventPatternSource.cs
Rx.NET/Source/src/System.Reactive/EventPatternSourceBase.cs
Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs
Rx.NET/Source/src/System.Reactive/Linq/Observable/FromEventPattern.cs
Rx.NET/Source/src/System.Reactive/Linq/Observable/Generate.cs
Rx.NET/Source/src/System.Reactive/Linq/QueryLanguage.Conversions.cs
Rx.NET/Source/src/System.Reactive/Linq/QueryLanguage.Events.cs
Rx.NET/Source/tests/Tests.System.Reactive.ApiApprovals/Api/ApiApprovalTests.Core.verified.cs

Continue to massage the `FromEvent` stuff and its ripple effect on public APIs. Also fixing a few other warnings found in the process.
Progress to 0 suppressions: `47/337` left

Fix #nullable warnings for FromEvent et al.

---

Rx.NET/Source/src/System.Reactive/Internal/HalfSerializer.cs
Rx.NET/Source/src/System.Reactive/Linq/Observable/DelaySubscription.cs
Rx.NET/Source/src/System.Reactive/Linq/Observable/Finally.cs
Rx.NET/Source/src/System.Reactive/Linq/Observable/GetEnumerator.cs
Rx.NET/Source/src/System.Reactive/Linq/Observable/OnErrorResumeNext.cs
Rx.NET/Source/src/System.Reactive/Linq/Observable/Range.cs
Rx.NET/Source/src/System.Reactive/Linq/Observable/Repeat.cs
Rx.NET/Source/src/System.Reactive/Linq/Observable/RepeatWhen.cs
Rx.NET/Source/src/System.Reactive/Linq/Observable/RetryWhen.cs
Rx.NET/Source/src/System.Reactive/Linq/Observable/SkipUntil.cs
Rx.NET/Source/src/System.Reactive/Linq/Observable/TakeUntil.cs
Rx.NET/Source/src/System.Reactive/Linq/Observable/TakeUntilPredicate.cs
Rx.NET/Source/src/System.Reactive/Linq/Observable/TimeInterval.cs
Rx.NET/Source/src/System.Reactive/Linq/Observable/Timeout.cs
Rx.NET/Source/src/System.Reactive/Linq/Observable/Timer.cs
Rx.NET/Source/tests/Tests.System.Reactive/Tests/Concurrency/EventLoopSchedulerTest.cs
Rx.NET/Source/tests/Tests.System.Reactive/Tests/Linq/Observable/ObserveOnTest.cs

A few more operators being addressed.
Progress to 0 suppressions: `33/337` left

More #nullable for query operators.

---

Rx.NET/Source/src/System.Reactive/Subjects/AsyncSubject.cs
Rx.NET/Source/src/System.Reactive/Subjects/BehaviorSubject.cs
Rx.NET/Source/src/System.Reactive/Subjects/ReplaySubject.cs
Rx.NET/Source/src/System.Reactive/Subjects/Subject.cs
Rx.NET/Source/tests/Tests.System.Reactive.ApiApprovals/Api/ApiApprovalTests.Core.verified.cs

One public API change for `TryGetValue` on `AsyncSubject<T>`.

Enable #nullable for subjects.

---

Rx.NET/Source/src/System.Reactive/Concurrency/ConcurrencyAbstractionLayerImpl.Windows.cs
Rx.NET/Source/src/System.Reactive/Concurrency/ConcurrencyAbstractionLayerImpl.cs
Rx.NET/Source/src/System.Reactive/Internal/ExceptionServices.Default.cs
Rx.NET/Source/src/System.Reactive/Internal/ExceptionServicesImpl.cs
Rx.NET/Source/src/System.Reactive/Internal/HostLifecycleNotifications.Windows.cs
Rx.NET/Source/src/System.Reactive/Joins/ActivePlan.cs
Rx.NET/Source/src/System.Reactive/Joins/Plan.cs
Rx.NET/Source/src/System.Reactive/ObservableQuery.cs
Rx.NET/Source/src/System.Reactive/Subjects/ConnectableObservable.cs

And also simplify some other stuff.

Seal some types

---

Rx.NET/Source/tests/Tests.System.Reactive/Tests/Concurrency/ControlSchedulerTest.cs
Rx.NET/Source/tests/Tests.System.Reactive/Tests/Concurrency/CurrentThreadSchedulerTest.cs
Rx.NET/Source/tests/Tests.System.Reactive/Tests/Concurrency/ImmediateSchedulerTest.cs
Rx.NET/Source/tests/Tests.System.Reactive/Tests/Concurrency/NewThreadSchedulerTest.cs
Rx.NET/Source/tests/Tests.System.Reactive/Tests/Concurrency/VirtualSchedulerTest.cs

Follow-up for the flaky UI tests by re-enabling various tests and simplifying some more.

Re-enable some tests

---

Rx.NET/Integration/WindowsDesktopTests/WindowsDesktopTests.csproj

Only specify usewpf/usewinforms for the platforms where we're testing it

---

AsyncRx.NET/System.Reactive.Async.Linq/System/Reactive/Linq/Operators/Append.cs
AsyncRx.NET/System.Reactive.Async.Linq/System/Reactive/Linq/Operators/Catch.cs
AsyncRx.NET/System.Reactive.Async.Linq/System/Reactive/Linq/Operators/Concat.cs
AsyncRx.NET/System.Reactive.Async.Linq/System/Reactive/Linq/Operators/DefaultIfEmpty.cs
AsyncRx.NET/System.Reactive.Async.Linq/System/Reactive/Linq/Operators/Delay.cs
AsyncRx.NET/System.Reactive.Async.Linq/System/Reactive/Linq/Operators/DelaySubscription.cs
AsyncRx.NET/System.Reactive.Async.Linq/System/Reactive/Linq/Operators/Distinct.cs
AsyncRx.NET/System.Reactive.Async.Linq/System/Reactive/Linq/Operators/DistinctUntilChanged.cs
AsyncRx.NET/System.Reactive.Async.Linq/System/Reactive/Linq/Operators/Do.cs
AsyncRx.NET/System.Reactive.Async.Linq/System/Reactive/Linq/Operators/DoWhile.cs
AsyncRx.NET/System.Reactive.Async.Linq/System/Reactive/Linq/Operators/ElementAt.cs
AsyncRx.NET/System.Reactive.Async.Linq/System/Reactive/Linq/Operators/ElementAtOrDefault.cs
AsyncRx.NET/System.Reactive.Async.Linq/System/Reactive/Linq/Operators/Finally.cs
AsyncRx.NET/System.Reactive.Async.Linq/System/Reactive/Linq/Operators/First.cs
AsyncRx.NET/System.Reactive.Async.Linq/System/Reactive/Linq/Operators/FirstOrDefault.cs

For some reason, lamdas passed to a particular overload of Create were not marked static during my recent work.

Mark more lambdas static

---

Rx.NET/Source/src/System.Reactive/Linq/Observable/Throttle.cs

Fix #1493.

---

README.md

In response to: https://github.com/dotnet/reactive/issues/1476#issuecomment-771007749

Update Rx 5.x supported platform in README

---

Rx.NET/Source/Directory.build.props

Use snupkg instead of embedded symbols

---

Rx.NET/Documentation/IntroToRx/00_Foreword.md
Rx.NET/Documentation/IntroToRx/01_WhyRx.md
Rx.NET/Documentation/IntroToRx/02_KeyTypes.md
Rx.NET/Documentation/IntroToRx/03_LifetimeManagement.md
Rx.NET/Documentation/IntroToRx/04_CreatingObservableSequences.md
Rx.NET/Documentation/IntroToRx/05_Filtering.md
Rx.NET/Documentation/IntroToRx/06_Inspection.md
Rx.NET/Documentation/IntroToRx/07_Aggregation.md
Rx.NET/Documentation/IntroToRx/08_Transformation.md
Rx.NET/Documentation/IntroToRx/09_SideEffects.md
Rx.NET/Documentation/IntroToRx/10_LeavingTheMonad.md
Rx.NET/Documentation/IntroToRx/11_AdvancedErrorHandling.md
Rx.NET/Documentation/IntroToRx/12_CombiningSequences.md
Rx.NET/Documentation/IntroToRx/13_TimeShiftedSequences.md
Rx.NET/Documentation/IntroToRx/14_HotAndColdObservables.md
Rx.NET/Documentation/IntroToRx/15_SchedulingAndThreading.md
Rx.NET/Documentation/IntroToRx/16_TestingRx.md
Rx.NET/Documentation/IntroToRx/17_SequencesOfCoincidence.md
Rx.NET/Documentation/IntroToRx/18_UsageGuidelines.md
Rx.NET/Documentation/IntroToRx/19_DispellingMyths.md
Rx.NET/Documentation/IntroToRx/20_Disposables.md

Hello and thank you for contributing to dotnet/reactive. Before you proceed by creating a pull request (PR):
> Please make sure your contribution is in line with the project's [licensing model](https://github.com/dotnet/reactive/blob/main/LICENSE) and
your employment allows you to contribute to open source. ✅ 
> Please sign the [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/reactive?pullRequest=1101) in case the CLA bot asks you
for being a new contributor. ✅ (Approved Thu, 14 May 2015)
> Please make sure you target the `main` branch when creating the PR. ✅ 
This PR addresses #836 and #1563 .
Discussion has occurred offsite, and an agreement has been made for myself (@LeeCampbell) to hand over the IntroToRx content to the …

Importing IntroToRx.com content

---

README.md

Fix for #2076 - Update Slack link

---

Rx.NET/Source/version.json

We are planning at least one feature that will add to the API surface area, so we need a minor version bump.

Update version.json to 6.1.0
