Rx.NET/Source/System.Reactive.Linq/Reactive/Linq/Observable/Buffer.cs
We're using the following Rx subscription in our system:
_subscription = _subject.Buffer(timeSpan: TimeSpan.FromMilliseconds(250), count: 1500)
.ObserveOn(TaskPoolScheduler.Default)
.Subscribe(list => Handler(list),
ex => /* OnError Logging */,
() => /* OnComplete Logging */);
Recently, we noticed that under certain conditions the OnNext action would stop being called every timeSpan (250ms in this case). This meant that anywhere up to 1499 items could be buffered but not passed to the observer until the 1500 count was reached. This caused a *very serious* bug in one of our use cases because only 4000 items were passed through the Buffer during its lifetime, so the last 500 items would never come out of the other side! 
I can reproduce the issue within 3-4 runs and have tried using …
=> Fixed race condition in Buffer where timer could stop ticking

Rx.NET/Source/System.Reactive.Core/Reactive/Disposables/CompositeDisposable.cs, Rx.NET/Source/Tests.System.Reactive/Tests/Disposables/DisposableTests.cs
This pull request enforces that null values can not be added to the CompositeDisposable type via the constructors. Closes issue #73
=> Ensuring consistent CompositeDisposable invariant

Ix.NET/Source/System.Interactive.Async/AsyncEnumerable.Single.cs, Ix.NET/Source/System.Interactive.Async/TaskExt.cs, Ix.NET/Source/System.Interactive/EnumerableEx.Single.cs, Ix.NET/Source/Tests/AsyncTests.Single.cs, Ix.NET/Source/Tests/TaskExtTests.cs, Ix.NET/Source/Tests/Tests.Single.cs, Ix.NET/Source/Tests/Tests.csproj
1. AsyncEnumerable. TakeLast(0) takes forever to return.
new int[] { 1 }.ToAsyncEnumerable().TakeLast(0).ForEachAsync(_ => { }).Wait()
2. AsyncEnumerable Task extension class method throws wrapped AggregatedException which is not useful if someone wants to understand root cause of the problem.
See the enitre thread here - https://github.com/aspnet/EntityFramework/issues/2192
=> This includes two fixes for 1)TakeLast(0) take infinite time to return. 2)https://github.com/aspnet/EntityFramework/issues/2192

Ix.NET/Source/NuSpecs/System.Interactive.Async.Providers.nuspec, Ix.NET/Source/NuSpecs/System.Interactive.Async.nuspec, Ix.NET/Source/NuSpecs/System.Interactive.Providers.nuspec, Ix.NET/Source/NuSpecs/System.Interactive.nuspec, Ix.NET/Source/build-new.ps1, Rx.NET/Source/NuSpecs/Microsoft.Reactive.Testing.nuspec, Rx.NET/Source/NuSpecs/System.Reactive.Core.nuspec, Rx.NET/Source/NuSpecs/System.Reactive.Experimental.nuspec, Rx.NET/Source/NuSpecs/System.Reactive.Interfaces.nuspec, Rx.NET/Source/NuSpecs/System.Reactive.Linq.nuspec, Rx.NET/Source/NuSpecs/System.Reactive.Observable.Aliases.nuspec, Rx.NET/Source/NuSpecs/System.Reactive.PlatformServices.nuspec, Rx.NET/Source/NuSpecs/System.Reactive.Providers.nuspec, Rx.NET/Source/build-new.ps1
This addresses #190 by removing `portable-` lib folders and relying on NuGet 2.12's support for `netstandard1.0` in VS 2012/2013
=> Remove portable- from NuSpecs 

Ix.NET/Source/NuSpecs/System.Interactive.Async.Providers.nuspec, Ix.NET/Source/NuSpecs/System.Interactive.Async.nuspec, Ix.NET/Source/NuSpecs/System.Interactive.Providers.nuspec, Ix.NET/Source/NuSpecs/System.Interactive.nuspec, Ix.NET/Source/build-new.ps1, Rx.NET/Source/NuSpecs/Microsoft.Reactive.Testing.nuspec, Rx.NET/Source/NuSpecs/System.Reactive.Core.nuspec, Rx.NET/Source/NuSpecs/System.Reactive.Experimental.nuspec, Rx.NET/Source/NuSpecs/System.Reactive.Interfaces.nuspec, Rx.NET/Source/NuSpecs/System.Reactive.Linq.nuspec, Rx.NET/Source/NuSpecs/System.Reactive.Observable.Aliases.nuspec, Rx.NET/Source/NuSpecs/System.Reactive.PlatformServices.nuspec, Rx.NET/Source/NuSpecs/System.Reactive.Providers.nuspec, Rx.NET/Source/build-new.ps1
Put some dependency groups in that'll stop packages.config users from getting a lot of dependencies. Also ensures we work with NuGet 2.8.6 until 2.12 is available with netstandard support in VS 2012+
=> Ensure good experience for packages.config users

Ix.NET/Source/NuSpecs/System.Interactive.Async.Providers.nuspec, Ix.NET/Source/NuSpecs/System.Interactive.Async.nuspec, Ix.NET/Source/NuSpecs/System.Interactive.Providers.nuspec, Ix.NET/Source/NuSpecs/System.Interactive.nuspec, Ix.NET/Source/build-new.ps1, Rx.NET/Source/NuSpecs/Microsoft.Reactive.Testing.nuspec, Rx.NET/Source/NuSpecs/System.Reactive.Core.nuspec, Rx.NET/Source/NuSpecs/System.Reactive.Experimental.nuspec, Rx.NET/Source/NuSpecs/System.Reactive.Interfaces.nuspec, Rx.NET/Source/NuSpecs/System.Reactive.Linq.nuspec, Rx.NET/Source/NuSpecs/System.Reactive.Observable.Aliases.nuspec, Rx.NET/Source/NuSpecs/System.Reactive.PlatformServices.nuspec, Rx.NET/Source/NuSpecs/System.Reactive.Providers.nuspec, Rx.NET/Source/build-new.ps1
as earlier versions choke on multiple `netstandard` refs in the package
=> Set minClientVersion to 2.12 

Ix.NET/Source/System.Interactive/EnumerableEx.Single.cs
Index increment is checked in other LINQ methods.
=> In EnumerableEx.ForEach, index increment should be checked.

Ix.NET/Source/System.Interactive/EnumerableEx.Exceptions.cs, Ix.NET/Source/Tests/Tests.Exceptions.cs
I fixed Ix Catch methods with Array.
At 2252cb4, next test passes.
```csharp
[TestMethod]
public void Catch5()
{
var xss = new[] { Enumerable.Range(0, 5), Enumerable.Range(5, 5) };
var res = EnumerableEx.Catch(xss);
Assert.IsTrue(res.SequenceEqual(Enumerable.Range(0, 5)));
}
```
But next test failed.
```csharp
[TestMethod]
public void Catch5_Array()
{
var xss = new[] { new[] { 0, 1, 2, 3, 4 }, new[] { 5, 6, 7, 8, 9 } };
var res = EnumerableEx.Catch(xss);
Assert.IsTrue(res.SequenceEqual(Enumerable.Range(0, 5)));
}
```
`IEnumerator<T>` `Current` property when `IEnumerator<T>` `MoveNext()` return false is undefined.
Array throws Exception.`List<T>` returns defaualt(T).
Unexpected throwing exceptions are happen at [here](https://github.com/Reactive-Extensions/Rx.NET/blob/master/Ix.NET/Source/S …
=> Fix Ix Catch method invalid behaviour with Array.

Rx.NET/Source/System.Reactive.Linq/Reactive/Linq/Observable.Time.cs
I fixed the "samper" typo in the XML documentation comment to correctly refer to the `sampler` function parameter.
=> Fix spelling error in documentation comment.

Ix.NET/Source/Ix.NET.sln, Ix.NET/Source/global.json, Rx.NET/Source/global.json
After installing VS2015 Update 3 and the latest stable VS tooling for .NET Core, you'll probably see this message when opening the Rx.NET solution:
This PR makes the error go away, and also adds some of the solution-level changes to the Ix.NET solution so these have a consistent structure.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/reactive-extensions/rx.net/208)
=> VS environment cleanup

Ix.NET/Source/System.Interactive.Async/ToObservable.cs, Ix.NET/Source/Tests/AsyncTests.Conversions.cs
This would happen whenever an IObserver<T>.OnNext would dispose its subscription within a call to OnNext. The built in AnonymousAsyncEnumerator<T> checks whether it's already disposed, however, not every user code might handle canceled tokens that gracefully. Also, the continuation of MoveNext will not be scheduled anyway.
=> ToObservable: Do not call MoveNext with an already canceled CancellationToken

Rx.NET/Source/System.Reactive.Core/Reactive/Disposables/MultipleAssignmentDisposable.cs
This PR removes the locking from `MultipleAssignmentDisposable` and uses "plain" Volatile/Interlocked actions.
=> Lock free MultipleAssignmentDisposable

Ix.NET/Source/System.Interactive.Async/AsyncIterator.cs, Ix.NET/Source/Tests/AsyncTests.Bugs.cs
Since AsyncIterator is not public, the problem here only arises when a reference of AsyncIterator is explicitly cast to IDisposable and disposed of - in IoC-containers like Autofac, this is a common scenario since it keeps track of all created disposables so this is gonna explode somewhere without this fix.
=> In AsyncIterator.Dispose, check whether cancellationTokenSource is null

Rx.NET/Source/System.Reactive.Linq/Reactive/Linq/Observable/WithLatestFrom.cs
As I reported in #227, setting a volatile `hasLatest` doesn't ensure proper visibility of the latest value and one needs at least an ordered store for the whole element (by boxing it and writing the reference in with an ordered store).
**Cost of correctness**: one boxing and one unboxing of structure types.
**Possible tradeoff choice**: using `Volatile.Write` instead of `Interlocked.Exchange`; both are correct but the former may only become visible a bit delayed (once the CPU write buffer is emitted) whereas the latter is "immediately" visible to other cores.
=> Fix WithLatestFrom potential memory visibility issues

Rx.NET/Source/System.Reactive.Linq/Reactive/Threading/Tasks/TaskObservableExtensions.cs
We use the ToTask-extension a lot in our code and found it rather expensive wrt. object allocations. Looking into the code, I found that by implementing a custom IObserver, creation of closures and delegates can be avoided. I think even without anonymous lambdas, the code is still straghtforward and easy to read.
=> Reduce number of allocations (closures, delegates) in TaskObservableExtensions.ToTask

Ix.NET/Source/System.Interactive.Async.Providers/IOrderedAsyncQueryable.cs, Ix.NET/Source/Tests/AsyncEnumerableQueryTest.cs
If a class like AsyncEnumerableQuery implements IOrderedAsyncQueryable<T>, it does not automatically implement IOrderedAsyncQueryable<T>, which can be a problem within untyped code.
Fixes #301
=> Let IOrderedAsyncQueryable<T> implement IOrderedAsyncQueryable

Ix.NET/Source/System.Interactive.Async/ToObservable.cs
As described in #319, concurrent cancellation of async iterators may lead to unexpected exceptions. At least in some places (e.g. those where the `Try...` methods of `TaskCompletionSource` may be used), an easy fix is possible.
=> AsyncEnumerable.ToObservable: Use Try...-methods on TaskCompletionSources to avoid unexpected exceptions when the iterator is cancelled.

Rx.NET/Source/src/System.Reactive/Disposables/AnonymousDisposable.cs, Rx.NET/Source/src/System.Reactive/Disposables/ContextDisposable.cs, Rx.NET/Source/src/System.Reactive/Disposables/ScheduledDisposable.cs, Rx.NET/Source/src/System.Reactive/Disposables/SingleAssignmentDisposable.cs, Rx.NET/Source/src/System.Reactive/Disposables/StableCompositeDisposable.cs, Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Merge.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/SelectMany.cs, Rx.NET/Source/src/System.Reactive/Subjects/ReplaySubject.cs, Rx.NET/Source/src/System.Reactive/Subjects/Subject.cs
These suppressions predate Roslyn where this warning is no longer raised. See https://github.com/dotnet/roslyn/blob/ab534ba4afb74cf4c3fa0748102217eab2f52f9a/src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_Warnings.cs#L56.
=> Use of Interlocked on volatile fields no longer raises CS0420

Rx.NET/Source/src/System.Reactive/Concurrency/TaskHelpers.cs
Another remnant from the early days without the TPL.
=> Removing TASKEX symbol

Rx.NET/Source/src/System.Reactive/Concurrency/ConcurrencyAbstractionLayerImpl.cs, Rx.NET/Source/src/System.Reactive/Concurrency/LocalScheduler.TimerQueue.cs, Rx.NET/Source/src/System.Reactive/Concurrency/ThreadPoolScheduler.cs
All target platforms have `HashSet<T>` now.
=> Removing checks for absence of HashSet<T>

Rx.NET/Source/src/System.Reactive/Concurrency/Synchronization.ObserveOn.cs, Rx.NET/Source/src/System.Reactive/Concurrency/Synchronization.cs, Rx.NET/Source/src/System.Reactive/Concurrency/SynchronizationContextScheduler.cs, Rx.NET/Source/src/System.Reactive/Disposables/ContextDisposable.cs, Rx.NET/Source/src/System.Reactive/Internal/SynchronizationContextExtensions.cs, Rx.NET/Source/src/System.Reactive/Linq/IQueryLanguage.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable.Concurrency.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/ObserveOn.cs, Rx.NET/Source/src/System.Reactive/Linq/QueryLanguage.Concurrency.cs, Rx.NET/Source/src/System.Reactive/Observer.Extensions.cs
Every targeted platform has `SynchronizationContext` so we no longer need to `#if` check for it.
=> Removing checks for absence of SynchronizationContext

Rx.NET/Source/src/System.Reactive/Concurrency/ConcurrencyAbstractionLayerImpl.Windows.cs, Rx.NET/Source/src/System.Reactive/Concurrency/ConcurrencyAbstractionLayerImpl.cs, Rx.NET/Source/src/System.Reactive/Concurrency/EventLoopScheduler.cs, Rx.NET/Source/src/System.Reactive/Concurrency/NewThreadScheduler.cs, Rx.NET/Source/src/System.Reactive/Concurrency/TaskPoolScheduler.cs, Rx.NET/Source/src/System.Reactive/Concurrency/ThreadPoolScheduler.cs, Rx.NET/Source/src/System.Reactive/Internal/StopwatchImpl.cs, Rx.NET/Source/tests/Tests.System.Reactive/Tests/Concurrency/EventLoopSchedulerTest.cs, Rx.NET/Source/tests/Tests.System.Reactive/Tests/Concurrency/NewThreadSchedulerTest.cs, Rx.NET/Source/tests/Tests.System.Reactive/Tests/Concurrency/StopwatchTest.cs, Rx.NET/Source/tests/Tests.System.Reactive/Tests/Concurrency/TaskPoolSchedulerTest.cs, Rx.NET/Source/tests/Tests.System.Reactive/Tests/Concurrency/ThreadPoolSchedulerTest.cs, Rx.NET/Source/tests/Tests.System.Reactive/Tests/DefaultConcurrencyAbstractionLayerTest.cs
`Stopwatch` is available on all platforms.
=> Removing check for absence of Stopwatch

Rx.NET/Source/src/System.Reactive/Internal/PriorityQueue.cs
Another remnant from very old build flavors in the 1.x days.
=> Removing check for 64-bit interlocked instructions

Rx.NET/Source/src/System.Reactive/Concurrency/SchedulerOperation.cs, Rx.NET/Source/src/System.Reactive/Disposables/AnonymousDisposable.cs, Rx.NET/Source/src/System.Reactive/Internal/HostLifecycleService.cs, Rx.NET/Source/src/System.Reactive/Internal/SystemClock.Default.cs, Rx.NET/Source/src/System.Reactive/Platforms/UWP/Foundation/AsyncInfoToObservableBridge.cs
Null-conditional delegate invocation.
=> Delegate invocation using C# 6.0 syntax

Rx.NET/Source/src/System.Reactive/Joins/QueryablePattern.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/FromEvent.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/FromEventPattern.cs, Rx.NET/Source/src/System.Reactive/Linq/QueryLanguage.Events.cs, Rx.NET/Source/src/System.Reactive/ObservableQuery.cs, Rx.NET/Source/tests/Tests.System.Reactive/Tests/Concurrency/AsyncLockTest.cs, Rx.NET/Source/tests/Tests.System.Reactive/Tests/PrivateTypesTest.cs
More places where use of `nameof` is applicable.
=> Using nameof when looking up members through reflection

Rx.NET/Source/src/System.Reactive/Internal/SystemClock.cs
This type is now available on all platforms, doing away with the need to have a backport and conditional compilation.
=> Removing checks for WeakReference<T>

Rx.NET/Source/src/System.Reactive/Concurrency/EventLoopScheduler.cs, Rx.NET/Source/src/System.Reactive/Internal/PushPullAdapter.cs, Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Delay.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/GetEnumerator.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/GroupByUntil.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Latest.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Next.cs, Rx.NET/Source/src/System.Reactive/Linq/QueryLanguage.Blocking.cs, Rx.NET/Source/tests/Tests.System.Reactive/Stress/Core/Schedulers/EventLoop.cs, Rx.NET/Source/tests/Tests.System.Reactive/Tests/Concurrency/EventLoopSchedulerTest.cs, Rx.NET/Source/tests/Tests.System.Reactive/Tests/Concurrency/ThreadPoolSchedulerTest.cs, Rx.NET/Source/tests/Tests.System.Reactive/Tests/Linq/ObservableConcurrencyTest.cs, Rx.NET/Source/tests/Tests.System.Reactive/Tests/ObserverTest.cs
Removing `NO_CDS` to check for the presence of concurrent data structures and concurrent APIs which are now available on all target platforms.
=> Removing checks for concurrent APIs

Rx.NET/Source/src/System.Reactive/Concurrency/CatchScheduler.cs, Rx.NET/Source/src/System.Reactive/Concurrency/DisableOptimizationsScheduler.cs, Rx.NET/Source/src/System.Reactive/Concurrency/SchedulerWrapper.cs
`ConditionalWeakTable<,>` is available on all platforms, so we can do away with the conditional compilation.
=> Removing conditional use of ConditionalWeakTable

Rx.NET/Source/src/System.Reactive/Concurrency/CurrentThreadScheduler.cs
The `ThreadStatic` attribute is available on all platforms. We should consider using `ThreadLocal<T>` at some point.
=> Removing conditional usage of TLS

Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Services.cs, Rx.NET/Source/src/System.Reactive/Internal/Helpers.cs, Rx.NET/Source/src/System.Reactive/Internal/SafeObserver.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Catch.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/OnErrorResumeNext.cs, Rx.NET/Source/src/System.Reactive/Linq/Qbservable.cs, Rx.NET/Source/src/System.Reactive/Linq/QbservableEx.cs, Rx.NET/Source/src/System.Reactive/Linq/QueryLanguage.Single.cs, Rx.NET/Source/src/System.Reactive/Linq/QueryLanguage.StandardSequenceOperators.cs, Rx.NET/Source/src/System.Reactive/Linq/QueryLanguage.Time.cs, Rx.NET/Source/src/System.Reactive/Observable.Extensions.cs, Rx.NET/Source/src/System.Reactive/ObservableQuery.cs, Rx.NET/Source/src/System.Reactive/Subjects/Subject.cs
Some trivial changes to use more C# 7.0 features.
=> Using C# 7 pattern matching features

Rx.NET/Source/Directory.build.props
This enables SourceLink again, but uses `SourceLink.Create.CommandLine` which is new to 2.1. It simply uses the git command line and not dotnet.
I downloaded the nupkg and validated that it works:
https://ci.appveyor.com/project/ctaggart/rx-net/build/4.0.0-develop-test.319.build.18
```
dotnet sourcelink test C:\Users\CameronTaggart\Downloads\System.Reactive.4.0.0-develop-test.319.nupkg
sourcelink test passed: lib/netstandard1.3/System.Reactive.dll
sourcelink test passed: lib/net45/System.Reactive.dll
sourcelink test passed: lib/net46/System.Reactive.dll
sourcelink test passed: lib/uap10.0/System.Reactive.dll
```
=> use SourceLink.Create.CommandLine

Ix.NET/Source/Directory.build.props, Ix.NET/Source/NuGet.Config, Ix.NET/Source/build-new.ps1, Ix.NET/Source/version.json, NuGet.Config, Rx.NET/Source/Directory.build.props, Rx.NET/Source/NuGet.Config, Rx.NET/Source/build-new.ps1, Rx.NET/Source/facades/Directory.build.props, Rx.NET/Source/version.json
This task supports two features we need:
1. different versions per project, Ix and Rx.
2. supports dotnet cli and removes the msbuild requirement.
=> Switch to use Nerdbank.Gitversioning

README.md
The NuGet version badges now link to NuGet instead of opening the image in new tab
=> Make NuGet badges link to NuGet

Rx.NET/Source/src/System.Reactive/Internal/Constants.cs
This removes misleading message of requiring a reference to System.Reactive.PlatformServices, given it is only a facade library from v4.
=> Update Obsolete message for Scheduler

Ix.NET/Source/Directory.build.props, Ix.NET/Source/System.Interactive.Async.Providers/System.Interactive.Async.Providers.csproj, Ix.NET/Source/System.Interactive.Async/System.Interactive.Async.csproj, Ix.NET/Source/System.Interactive.Providers/System.Interactive.Providers.csproj, Ix.NET/Source/System.Interactive/System.Interactive.csproj, Rx.NET/Source/Directory.build.targets
Enabled by https://github.com/dotnet/sdk/commit/24db8f1c96dc2857fcecce7f274f1aa94f0017f8
This works for me on dotnet 2.1.1
=> Specify DebugType in directory.build.props

Rx.NET/Source/src/System.Reactive/System.Reactive.csproj, Rx.NET/Source/version.json
Fixes issue
`error CS0012: The type 'Dispatcher' is defined in an assembly that is not referenced. You must add a reference to assembly 'WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.`
=> Add explicit windowsbase reference

Rx.NET/Source/src/System.Reactive/Linq/Observable.Multiple.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/SkipUntil.cs, Rx.NET/Source/tests/Tests.System.Reactive/Tests/Linq/ObservableMultipleTest.cs
In case source and other emit elements right away, the first element of source is not missed out.
=> Reverse subscription order in SkipUntil

Rx.NET/Source/src/System.Reactive/Concurrency/AsyncLock.cs
This PR improves the `AsyncLock` class' logic:
- Avoid the cost of allocating a `queue` upfront in case there is no actual concurrency involved.
- Clearing that queue is more efficient by setting the reference to `null`.
- Enqueueing an `Action` when the "lock" is not held should not go through the queue because it can be executed immediately.
- Changed the lock to `this` (as `queue` can now be `null`). I've seen other places with `guard = new object()` but that's an allocation and `this` is available. Not sure what the policy is given that `AsyncLock` is public. If it was `internal` or have such copy, I'm sure such shortcuts could be safely taken.
=> 4.x: Improve the logic of AsyncLock

Rx.NET/Source/src/System.Reactive/Disposables/CompositeDisposable.cs
This PR cleans up the internal logic of `CompositeDisposable` by avoiding some allocations and making sure publicly visible state is available in a thread-safe manner.
The main safety offender was the `IsDisposed` reading the `_disposed` plain field without a barrier. Assuming the .NET memory modell is compatible with the C++ 11/Java memory model, such reads could be cached and the reader may never see `_disposed` turn true:
```cs
var composite = new CompositeDisposable();
handOff(composite);
while (!composite.IsDisposed) Thread.SpinWait();
// resume
```
without a barrier, this could end up like this:
```cs
var isDisposed = composite.IsDisposed;
while (!isDisposed) Thread.SpinWait();
```
and never complete.
=> 4.x: Improve and fix CompositeDisposable

Rx.NET/Source/src/System.Reactive/Linq/Observable/ConcatMany.cs, Rx.NET/Source/src/System.Reactive/Linq/QueryLanguage.Multiple.cs
This PR implements the `Concat(IObservable<IObservable<T>>)` directly in an inlined (less allocation and indirection) and lock-free fashion. (The original was delegated to `Merge(sources, 1)` which I'd assume has more overhead because dealing with an arbitrary max-concurrency requires a lot of work in Rx.NET too.)
I didn't add extra unit tests as this code is meant to be a drop-in replacement of the previous delegated version and is supposed to be well tested already on its own, right?
There is one scenario that I'm not sure about: where both the outer and the current inner sources signal an `OnError`, it is not expected the outer error to stop the inner sequence immediately, and whoever's error wins, that is signaled on the boundary between two inner sources. Either I happened to …
=> 4.x: Optimize Concat(IObservable<IObservable<T>>)

Rx.NET/Source/src/System.Reactive/Internal/ConcatSink.cs, Rx.NET/Source/src/System.Reactive/Internal/TailRecursiveSink.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Catch.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/OnErrorResumeNext.cs
This PR changes `TailRecursiveSink` to a lock-free algorithm as well as reduces the allocations in the class by inlining various `IDisposable` fields.
The aim of the class is to make sure `OnComplete` or `OnError` in `Concat`, `Catch` and various other operators don't trigger an infinite recursion but stay on the level. 
This could have been solved with a straightforward trampoline [like this `Concat` implementation](https://github.com/dotnet/reactive/pull/491/files), however, there is a small complication. The recursion may be not only on the termination side, but on the existence of the inner `IObservable`s. 
For example, to avoid yet another level of recursion due to graphs like `Concat(Concat(a, b), Concat(c, d))`, the `Extract` method can get another level of …
=> 4.x: Make TailRecursiveSink lock-free and have less allocations

Rx.NET/Source/src/System.Reactive/Linq/IQueryLanguage.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable.Binding.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/AutoConnect.cs, Rx.NET/Source/src/System.Reactive/Linq/Qbservable.Generated.cs, Rx.NET/Source/src/System.Reactive/Linq/QueryLanguage.Binding.cs, Rx.NET/Source/tests/Tests.System.Reactive/Tests/Linq/ObservableAutoConnectTest.cs
This PR adds the `AutoConnect` operator as an extension method on `IConnectableObservable`. The operator connects the source once the specified number of observers have subscribed to it.
This operator enables caching of items via `Replay()` without the need to call `Connect()` manually and avoid reconnection which would happen with `RefCount()`:
```cs
var cached = source.Replay().AutoConnect(2);
// connection happens only now
cached.Subscribe(Console.WriteLine);
// connection happens only now
cached.Subscribe(Console.WriteLine);
// some time later when the source has completed on its own
// this will not trigger a new connection
cached.Subscribe(Console.WriteLine);
```
Subscribers disposed won't dispose the connection. In case the connection itself should be disposed, it is made available …
=> 4.x: Add the IConnectableObservable.AutoConnect() operator

Rx.NET/Source/src/System.Reactive/Internal/AutoDetachObserver.cs
This PR inlines the `SingleAssignmentDisposable` behavior into the `AutoDetachObserver` to save on an allocation and the indirection.
=> 4.x: Improve AutoDetachObserver memory footprint

Rx.NET/Source/src/System.Reactive/Internal/PriorityQueue.cs
The `PriorityQueue._count` field was a static field shared between all instances the `PriorityQueue` of the same type argument. I can only assume this was thought as a tradeoff between having 8 more bytes per priority queue or trashing everybody else's cache who happen to be prioritizing on the same type argument.
This PR simply changes it to a per instance counter and also removes the `Interlocked.Increment` as the class itself is by no means thread-safe so it makes no sense to have the creation of a fresh index atomic in `Enqueue`.
=> 4.x: Fix PriorityQueue to not share a item ordering helper index

Rx.NET/Source/src/System.Reactive/Concurrency/Synchronization.ObserveOn.cs, Rx.NET/Source/src/System.Reactive/Concurrency/Synchronization.cs, Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs
This PR adds a new implementation of the `ObserveOn` operator that uses a newer lock-free algorithm and is implemented as a separate set of classes.
The reason for this is that the `SchedulerObserver` the old `ObserveOnObserver` relies upon offers some union of features required throughout the code, convoluting its internal implementation to accomodate for multiple things. Improving those would require significantly more code changes across the code base along with trying to figure out what their intent was.
=> 4.x: Replace ObserveOn(IScheduler) with a newer lock-free algorithm

Rx.NET/Source/src/System.Reactive/Subjects/AsyncSubject.cs
This PR changes `AsyncSubject` to be a lock-free implementation by using atomics.
Since the observable protocol forbids calling the `OnXXX` methods concurrently, there was no real need for the locked regions and it didn't protect against most races anyway.
Some complication is due to the disposability feature thus that explicit state has to be checked and the relevant exceptions thrown.
The observer management has been also replaced by a straight atomic copy-on-write logic so concurrent subscriptions and subscription-termination races are handled without blocking. Note that the original implementation used `ImmutableList.Add` which is by itself also copy-on-write thus this change should not worsen the overhead of tracking a lot of observers while the subject is active.
=> 4.x: Improve AsyncSubject by using lock-free methods

Rx.NET/Source/src/System.Reactive/Subjects/Subject.cs
The PR inlines the copy-on-write logic of the `Observer`/`ImmutableList` behavior of `Subject`, thus reducing the allocation (allocation of a new `Observer`, a new `ImmutableList` inside and a new array within that too) and indirection in the class.
=> 4.x: Improve Subject's observer tracking

Rx.NET/Source/src/System.Reactive/Linq/Observable/Amb.cs
This PR improves the `Amb` operator by reducing allocations and making it lock-free.
Note that the algorithm can be extended to `Amb` any number of sources.
=> 4.x: Improve Amb

Rx.NET/Source/src/System.Reactive/Linq/Observable/CombineLatest.Generated.tt, Rx.NET/Source/src/System.Reactive/Linq/Observable/Zip.Generated.tt
Fix for #458: The T4-templates for CombineLatest and Zip should override the correct method.
=> Fix T4-templates for CombineLatest and Zip

Rx.NET/Source/src/System.Reactive/Platforms/Desktop/Concurrency/ControlScheduler.cs
This PR adds some additional eager dispose checks to `ControlScheduler` to see if either the `Control` object or the returned `IDisposable` has been disposed.
Fixes: #269
=> 4.x: Have the ControlScheduler do more eager disposed checks

Rx.NET/Source/src/System.Reactive/Joins/ActivePlan.cs, Rx.NET/Source/tests/Tests.System.Reactive/Tests/Linq/Observable/WhenTest.cs
This PR fixes a crash due to key reuse in `ActivePlan` that prevents self-joins such as this:
```cs
var source = Observable.Range(1, 5);
Observable.When(
source.And(source).Then((a, b) => a + b)
)
.Subscribe(Console.WriteLine);
```
Without the fix, there is a crash:
```
System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
System.Reactive.Joins.ActivePlan.AddJoinObserver(IJoinObserver joinObserver)
System.Reactive.Joins.ActivePlan`2..ctor(JoinObserver`1 first, JoinObserver`1 second, Action`2 onNext, Action onCompleted)
System.Reactive.Joins.Plan`3.Activate(Dictionary`2 externalSubscriptions, IObserver`1 observer, Action`1 …
```
=> 4.x: Fix ActivePlan crashing with self-joins

README.md
Link to previous RxJS is potentially confusing and was onyl really useful while 5 was in beta. 
RxJS is now at v6, and can probably take care of describing it's own version history. Newcomers will mostly likely be looking for the latest version.
=> Update RxJS reference

Rx.NET/Source/src/System.Reactive/Concurrency/EventLoopScheduler.cs
This fixes a potential memory leak.
If _queue is empty after the item is removed from it, then _nextItem is never overriden and therefore keeps a reference to item.
Until another action is scheduled with a future due time, the item and all its associated state is kept in memory.
(cherry picked from commit 2679e8e9f10f2674cfa88fd7e13f7f1cea7d2172)
see also https://github.com/Reactive-Extensions/Rx.NET/pull/325
=> EventLoopScheduler: set _nextItem to null on Tick

Rx.NET/Source/src/System.Reactive/Runtime/CompilerServices/TaskObservableMethodBuilder.cs
Fix the following compile warning:
2>Runtime\CompilerServices\TaskObservableMethodBuilder.cs(206,30): warning CS1711: XML comment has a typeparam tag for 'T', but there is no type parameter by that name [D:\a\1\s\Rx.NET\Source\src\System.Reactive\System.Reactive.csproj]
=> Fix compile warning (CS1711) caused by class inline documentation

Rx.NET/Source/src/System.Reactive/System.Reactive.csproj
To write modern code and to reduce allocations throughout the code, reference System.ValueTuple for further reduction of allocations, use C# 7.1 to use value tuples without the need for explicit tuple component naming.
=> Enable ValueTuples without explicit component naming.

Rx.NET/Source/tests/Tests.System.Reactive.Uwp.DeviceRunner/Tests.System.Reactive.Uwp.DeviceRunner.csproj, Rx.NET/Source/tests/Tests.System.Reactive/Tests/ImmutableListTest.cs
The code should be tested when System.Reactive is visible to the test assembly which is exactly when it is signed (and not vice versa). The SIGNED-directive is thus added to the Uwp-DeviceRunner project.
=> Fix compiler directive in ImmutableListTest

Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs, Rx.NET/Source/tests/Tests.System.Reactive/Tests/Concurrency/SchedulerTest.cs
This will allow to pass state to a scheduled action to avoid closure allocation and allow for delegate caching.
Note this is based on changes from https://github.com/dotnet/reactive/pull/515 which should be merged before this PR.
=> Add scheduler extension for actions

Rx.NET/Source/tests/Tests.System.Reactive/Tests/Linq/Observable/UsingAsyncTest.cs
This PR fixes the race condition in the `UsingAsyncTest.UsingAsync_Simple` on the `done` flag which is not guaranteed to be set just after when the elements become available to the test thread.
Fixes: #414
=> 4.x: Fix race condition in UsingAsync_Simple unit test

Rx.NET/Source/src/System.Reactive/Linq/Observable/TakeUntil.cs
This PR updates the internal logic of the `TakeUntil` to use a lock-free signalling algorithm for all event types.
=> 4.x:  Rework TakeUntil with lock-free methods

Rx.NET/Source/src/System.Reactive/Concurrency/DefaultScheduler.cs, Rx.NET/Source/src/System.Reactive/Concurrency/ThreadPoolScheduler.cs, Rx.NET/Source/src/System.Reactive/Disposables/Disposable.cs, Rx.NET/Source/src/System.Reactive/Disposables/SingleAssignmentDisposable.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/TakeUntil.cs
TrySetSingle should be called SetSingle since it can throw, TrySetSingle however remains and returns a more meaningful result. Added more docs.
=> Revise Disposable-helpers

Ix.NET/Source/System.Interactive.Async.Tests/AsyncTests.Creation.cs, Ix.NET/Source/System.Interactive.Async/Create.cs
Make sure the dispose action executes at most once in `AsyncEnumeble.CreateEnumerator`.
Fixes: #471
=> Ix.Async: Dispose an AsyncEnumerator once.

Rx.NET/Source/src/System.Reactive/Linq/Observable/Delay.cs
This PR fixes a bug in `Delay` that can lead to an unwanted cancellation of the drain loop. In addition, the `IStopwatch.Elapsed` should be consistently read while holding the same lock.
The bug is that the `_cancelable` can be reset by the `IDisposable` of the very first task starting the drain loop while that drain loop already set the `IDisposable` for the next round. The first assignment then cancels the second run's cancellation token which then throws an `ObjectDisposedException` and the loop quits for good. Any queued items and terminal signals will then never be emitted.
The solution is to conditionally set that first `IDisposable` if the target is still null, otherwise the subsequent runs have set a newer one and nothing has to be done. The disposability is still intact in both …
=> 4.x: Fix Delay hanging due to wrong disposable-chain management

Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs, Rx.NET/Source/src/System.Reactive/Disposables/ScheduledDisposable.cs, Rx.NET/Source/tests/Tests.System.Reactive/Tests/Concurrency/SchedulerTest.cs
Rename and reorder the signature of the extension for schedule that takes an Action<TState> and a state. Reordering the signature without renaming would cause ambiguities.
=> Rename/reorder an extension for ISchedulers.

Rx.NET/Source/src/System.Reactive/Internal/ExceptionHelper.cs, Rx.NET/Source/src/System.Reactive/Internal/HalfSerializer.cs, Rx.NET/Source/tests/Tests.System.Reactive/Tests/Internal/ExceptionHelperTest.cs, Rx.NET/Source/tests/Tests.System.Reactive/Tests/Internal/HalfSerializerTest.cs
This PR adds two lock-free helper class to work with partial signal serialization and atomic exception management.
This is an efficient, lock-free serialization when the `OnNext` are still coming in sequentially but there could be a concurrent `OnError` or `OnCompleted` happening, for example, with `TakeUntil` or `SkipUntil`. These methods establish the correct sequential behavior.
Hosts a shared termination indication exception (similar to how `BooleanDisposable.True` is used for indicating a disposed `IDisposable` field).
In addition, it offers methods for atomically setting one Exception, swapping in a the terminal exception and getting back the last exception and the ability to aggregate exceptions until a terminal exception is swapped in. This latter feature can come in handy with …
=> 4.x: Add ExceptionHelper & HalfSerializer lock-free tools

Rx.NET/Source/tests/Tests.System.Reactive/Tests/Linq/Observable/SkipUntilTest.cs
Current behaviour can be considered buggy, but a change is breaking.
=> Add a test that asserts the current behaviour of SkipUntil.

Rx.NET/Source/src/System.Reactive/Disposables/RefCountDisposable.cs
This PR changes the `RefCountDisposable` to use lock-free algorithms which are based on atomic conditional state changes: changes in the number of child disposables and whether the main disposable can be disposed.
It works by using bit 31 in the `_count` as the indicator for disposing the main underlying disposable once all child disposables have been disposed. Bits 30-0 are then the number of active child disposables. Since the field is still `int` this allows atomic CAS operations on this composite bit-structure.
=> 4.x: Make RefCountDisposable lock-free 

Rx.NET/Source/src/System.Reactive/Concurrency/EventLoopScheduler.cs, Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Services.Emulation.cs, Rx.NET/Source/src/System.Reactive/Concurrency/Synchronization.ObserveOn.cs, Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Buffer.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Catch.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/CombineLatest.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Delay.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Finally.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/GroupBy.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/GroupByUntil.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Multicast.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Sample.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/SelectMany.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/SequenceEqual.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Skip.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/SkipUntil.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Switch.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Take.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/TakeLast.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/TakeUntil.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Throttle.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Timeout.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Using.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Window.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/WithLatestFrom.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Zip.cs
This PR inlines the two argument `StableCompositeDisposable.Create()` into the various `Sink` implementation, saving on allocation and indirection.
=> 4.x: Inline StableCompositeDisposable.Create into the Sinks

Rx.NET/Source/src/System.Reactive/Concurrency/EventLoopScheduler.cs, Rx.NET/Source/src/System.Reactive/Concurrency/HistoricalScheduler.cs, Rx.NET/Source/src/System.Reactive/Concurrency/VirtualTimeScheduler.cs, Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Delay.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/FromEventPattern.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/RefCount.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Zip.cs
This PR inlines the `Disposable.Create(Action)` invocations, saving on an allocation and some indirection.
=> 4.x: Inline Disposable.Create

Rx.NET/Source/src/System.Reactive/Concurrency/ConcurrencyAbstractionLayerImpl.cs, Rx.NET/Source/tests/Tests.System.Reactive/Tests/Concurrency/VirtualSchedulerTest.cs, Rx.NET/Source/tests/Tests.System.Reactive/Tests/Linq/Observable/DelayTest.cs
For some reason, dotCover would hang in various timed test which use the `DefaultScheduler`. I don't know why, but removing that empty `try-catch` along with the atomic dispose management solves the issue. 
In addition, the `Virtual_ThreadSafety()` was running extremely slow in its original form (more than 5 minutes). The reduced time amount and a more close thread-synchronization should be faster now while preserving the behavior under test.
=> 4.x: Fix timed delay hangs with dotCover and the DefaultScheduler

Rx.NET/Source/src/System.Reactive/Concurrency/DefaultScheduler.cs, Rx.NET/Source/src/System.Reactive/Concurrency/EventLoopScheduler.cs, Rx.NET/Source/src/System.Reactive/Concurrency/ImmediateScheduler.cs, Rx.NET/Source/src/System.Reactive/Concurrency/TaskPoolScheduler.cs, Rx.NET/Source/src/System.Reactive/Concurrency/ThreadPoolScheduler.Windows.cs, Rx.NET/Source/src/System.Reactive/Concurrency/ThreadPoolScheduler.cs, Rx.NET/Source/src/System.Reactive/Internal/AsyncLockObserver.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Buffer.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Window.cs
Save allocation of lots of closures and allow delegate caching!
=> Use the stateful overload of AsyncLock in some places.

Rx.NET/Source/src/System.Reactive/Linq/IQueryLanguage.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable.Binding.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/RefCount.cs, Rx.NET/Source/src/System.Reactive/Linq/Qbservable.Generated.cs, Rx.NET/Source/src/System.Reactive/Linq/QueryLanguage.Binding.cs, Rx.NET/Source/tests/Tests.System.Reactive.ApiApprovals/Api/ApiApprovalTests.Core.approved.txt, Rx.NET/Source/tests/Tests.System.Reactive/Tests/Linq/Observable/RefCountTest.cs
LazyRefCount connects like RefCount but may delay disconnection. This is useful whenever a lot of connect/disconnect cycles are expected within a short timespan but with a significant overhead in connecting/disconnecting.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/reactive-extensions/rx.net/133)
=>  Add lazy RefCount operator for IObservables.

Rx.NET/Source/tests/Tests.System.Reactive/Tests/Disposables/DisposableTests.cs
This PR improves the coverage of `System.Reactive.Disposables` components.
(Note: it took me 5 hours to confirm these which involved resetting dotCover multiple times then waiting for ReSharper to finish analyzing coverage data after 20+ minutes each.)
=> 4.x: Improve coverage of System.Reactive.Disposables

Rx.NET/Source/src/System.Reactive/Concurrency/CatchScheduler.cs, Rx.NET/Source/src/System.Reactive/Concurrency/ImmediateScheduler.cs, Rx.NET/Source/src/System.Reactive/Concurrency/LocalScheduler.TimerQueue.cs, Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Services.Emulation.cs, Rx.NET/Source/src/System.Reactive/Concurrency/SchedulerOperation.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Delay.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Generate.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Repeat.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/TakeLast.cs
Mainly in the Concurrency-namespace and across usages of schedulers.
=> Save more allocations of closures and enable more delegate caching.

Rx.NET/Source/src/System.Reactive/Concurrency/AsyncLock.cs
Seen this in build warnings. Oddly, VS didn't highlight it as being missing on my setup for this project (it does it in other projects of mine though).
=> 4.x: Add missing state XML comment in AsyncLock

Rx.NET/Source/src/System.Reactive/Internal/ObserverWithToken.cs, Rx.NET/Source/src/System.Reactive/Notification.cs, Rx.NET/Source/src/System.Reactive/Observable.Extensions.cs, Rx.NET/Source/src/System.Reactive/Platforms/Desktop/Linq/QueryLanguage.Remoting.cs
Inline the use of `AnonymousObserver` at various locations:
- `Subscribe` with `CancellationTokenSource`
- Remoting `Subscribe`.
Also make `Notification.OnCompletedNotification` static singleton; it is stateless so there is no reason to create an instance of it all the time.
=> 4.x: Inline AnonymousObserver use at places

Rx.NET/Source/facades/GlobalAssemblyVersion.cs, Rx.NET/Source/facades/System.Reactive.Core/TypeForwarders.Core.cs, Rx.NET/Source/facades/System.Reactive.Experimental/TypeForwarders.Experimental.cs, Rx.NET/Source/facades/System.Reactive.Interfaces/TypeForwarders.Interfaces.cs, Rx.NET/Source/facades/System.Reactive.Linq/TypeForwarders.Linq.cs, Rx.NET/Source/facades/System.Reactive.PlatformServices/TypeForwarders.PlatformServices.cs, Rx.NET/Source/facades/System.Reactive.Providers/TypeForwarders.Providers.cs, Rx.NET/Source/facades/System.Reactive.Runtime.Remoting/TypeForwarders.Remoting.cs, Rx.NET/Source/facades/System.Reactive.Windows.Forms/TypeForwarders.Forms.cs, Rx.NET/Source/facades/System.Reactive.Windows.Threading/TypeForwarders.Threading.cs, Rx.NET/Source/facades/System.Reactive.WindowsRuntime/TypeForwarders.WindowsRuntime.cs, Rx.NET/Source/src/System.Reactive/Linq/QueryDebugger.cs, Rx.NET/Source/tests/Tests.System.Reactive/Tests/ImmutableListTest.cs, Rx.NET/Source/tests/Tests.System.Reactive/Tests/Internal/PriorityQueueTest.cs, Rx.NET/Source/tests/Tests.System.Reactive/Tests/LicenseHeaderTest.cs
This PR adds an unit test that scans most `*.cs` files in the `Rx.NET` project for the existence of a license header:
```cs
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information.
```
It creates a list of such files and by default, the header is added to those files. The logic excludes certain type of `cs` files such as generated ones and designer ones.
I'm not 100% certain for the file path detection part. Works for me locally, which assumes the work directory will be somewhere below `Rx.NET`.
=> 4.x: Check for license header and add them

Rx.NET/Source/src/System.Reactive/Linq/Observable/ConcatMany.cs, Rx.NET/Source/tests/Tests.System.Reactive/Tests/ArgumentValidationTest.cs
This PR adds an automatic, reflection based validation that goes through an extension method host (such as `Observable` or `ObservableEx`) and tries to call the various methods with `null` arguments (depending on the argument type) to see if the implementation actually verifies it. In addition, if the return type is `IObservable`, the same null check is performed with `Subscribe(null)`.
This type of tests are scattered around in all operators already, so the only missing check found was in the new `ConcatMany` operator. Such automatic test helps in the future if new operators or overloads get added to the library and remind the developer for the need for such checks. The existing tests should remain as they are.
=> 4.x: Add reflection-based Argument-Null validation test

Rx.NET/Source/tests/Tests.System.Reactive/Tests/LicenseHeaderTest.cs
My Rx git repository happens to be in the directory `Rx.NET`. So the resulting global source path is:
`C:\Users\peter\Documents\src\Rx.NET\Rx.NET\Source`.
Unfortunately, that makes the license header test fail, because in the test, the second occurance of `Rx.NET` is searched for but the first one is found.
The PR fix this by using `LastIndexOf`, addditionally the test will now fail, if there is no occurance at all instead of silently passing.
=> Use LastIndexOf instead of IndexOf in LicenseHeaderTest

Rx.NET/Source/src/System.Reactive/Linq/Observable/Timeout.cs
Make the absolute and selector-based `Timeout` operators lock-free, similar to #546.
=> 4.x: Have Timeout(Absolute|Selector) use lock-free methods.

.editorconfig
The previous settings forced **all** files edited by Visual Studio to receive a newline at the end, including the approval text files. This had the side effect that accessing the `approved.txt` files would add a newline to the end which then would show up as an error when the approval tests run; the generated test file has no trailing newline and it seems it can't be added without from our side.
This PR limits this feature only to `*.cs` files so accessing other files won't mess them up.
=> Add new lines and space-indentation only to *.cs files

Rx.NET/Source/src/System.Reactive/Linq/IQueryLanguage.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable.Multiple.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/TakeUntilPredicate.cs, Rx.NET/Source/src/System.Reactive/Linq/Qbservable.Generated.cs, Rx.NET/Source/src/System.Reactive/Linq/QueryLanguage.Multiple.cs, Rx.NET/Source/tests/Tests.System.Reactive.ApiApprovals/Api/ApiApprovalTests.Core.approved.txt, Rx.NET/Source/tests/Tests.System.Reactive/Tests/Linq/Observable/TakeUntilTest.cs
Add the `TakeUntil` operator overload with a predicate that will complete the sequence after an item has been emitted and then the predicate returns true for it:
```cs
Observable.Range(1, 10)
.TakeUntil(item => item == 5)
.Subscribe(Console.WriteLine);
```
which prints 1 through 5 and completes.
There is a similar operator: `TakeWhile` which performs the check **before** the item is emitted.
This is one of the operators present in RxJava and mentioned in #489.
=> 4.x: Add the TakeUntil(Func<T, bool>) operator

Ix.NET/Source/System.Interactive.Async.Tests/AsyncTests.Exceptions.cs, Ix.NET/Source/System.Interactive.Async/Finally.cs, Ix.NET/Source/System.Interactive.Tests/Tests.Buffering.cs, Ix.NET/Source/System.Interactive/Share.cs
The `Share4` was disabled because disposing a yield return-based IEnumerator has no effect. The code has been turned into a manual implementation.
The `Finally6` was disabled likely because the cancellation token could not trigger the finally action in time or due to a missing token registration. The code has been extended to react to the token as well as making sure the operator remains safe with now a possible concurrent `MoveNextCore` and `Dispose`.
Fixes: #625
=> Ix: Allow Share to be disposed, Make Finally react to token cancellation

Rx.NET/Source/tests/Tests.System.Reactive/Tests/LicenseHeaderTest.cs
This makes the code look more portable. In reality it works on windows and since it use the unix path separator `/`, I think it already works on linux, even though I haven't test it on linux. (see #601)
=> Improve path creation in license header test

Rx.NET/Source/src/System.Reactive/Linq/Observable/ToObservable.cs
Done by using a ValueTuple instead of a dedicated state class and passing state to IScheduler.Schedule.
=> Save some allocations in ToObservable

Rx.NET/Source/src/System.Reactive/Linq/Observable/GroupJoin.cs
We save some allocations by using the same techniques as in earlier PRs.
=> Review GroupJoin

Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Recursive.cs
Remove the `index` field from the `InvokeRecBaseState` class as it is not needed and is a remnant from an earlier algorithm from #617.
=> 4.x: Remove unused field in InvokeRecBaseState

Rx.NET/Source/tests/Tests.System.Reactive.ApiApprovals/Api/ApiApprovalTests.cs, Rx.NET/Source/tests/Tests.System.Reactive.ApiApprovals/DiffPlexReporter.cs, Rx.NET/Source/tests/Tests.System.Reactive.ApiApprovals/Tests.System.Reactive.ApiApprovals.csproj
Currently, the VSTS CI runs of the build that contain API approval failures are poorly communicated due to ApprovalTests appearing to favor UI oriented diffing tools. I spent a bit of time investigating why it wasn't falling back to the Xunit2 "reporter" but, even if it used that correctly, it only points out a character position of where it deviated which still wasn't very useful.
Instead, I looked at adding a new reporter that would produce a minimal diff should the tests fail. This is what I have implemented in this PR.
Example output from build script:
```
Stack Trace:
at ApprovalTests.Approvers.FileApprover.Fail()
at ApprovalTests.Core.Approver.Verify(IApprovalApprover approver, IApprovalFailureReporter reporter)
at ApprovalTests.Approvals.Verify(IApprovalApprover approver, …
```
=> Update API approvals to report a small diff on failure

Rx.NET/Source/src/System.Reactive/Linq/Observable/MaxBy.cs
- Inline the selector and comparer callback fields into the sink.
- Don't initialize fields to their defaults.
- Clear the `_list` and `_lastKey` field on failure and completion.
=> 4.x: Improve MaxBy cleanup/initialization

Rx.NET/Source/src/System.Reactive/Linq/Observable/LongCount.cs
There is no reason to initialize the `_count` to its default zero value.
=> 4.x: LongCount() don't init to default zero

Rx.NET/Source/src/System.Reactive/Linq/Observable/OfType.cs
Use a more recent C# language feature.
=> 4.x: OfType() use pattern variable instead of double cast

Rx.NET/Source/src/System.Reactive/Linq/Observable/RefCount.cs
No need to initialize those fields to their default values.
=> 4.x: RefCount() don't init to the default values

Rx.NET/Source/src/System.Reactive/Linq/Observable/MinBy.cs
- Inline the selector and comparer callback fields into the sink.
- Don't initialize fields to their defaults.
- Clear the `_list` and `_lastKey` field on failure and completion.
=> 4.x: Improve MinBy() cleanup/initialization

Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs
Prerequisite for https://github.com/dotnet/reactive/pull/685.
=> Add timed non recursive scheduling extensions.

Rx.NET/Source/benchmarks/Benchmarks.System.Reactive/BufferCountBenchmark.cs, Rx.NET/Source/benchmarks/Benchmarks.System.Reactive/Program.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Buffer.cs, Rx.NET/Source/src/System.Reactive/Linq/QueryLanguage.Single.cs
This PR improves the counted `Buffer` operator by having dedicated exact (count == skip) and gapped (count < skip) implementations because these cases require only one buffer to be handled instead of the overhead of a queue holding at most one buffer.
The PR also adds a benchmark to verify the gains:
```
// * Summary *
Frequency=3418007 Hz, Resolution=292.5682 ns, Timer=TSC
[Host]     : .NET Framework 4.7.1 (CLR 4.0.30319.42000), 64bit RyuJIT-v4.7.255 8.0
DefaultJob : .NET Framework 4.7.1 (CLR 4.0.30319.42000), 64bit RyuJIT-v4.7.255 8.0
// Before
Method |     Mean |    Error |   StdDev |   Gen 0 | Allocated |
-------- …
```
=> 4.x: Improve Buffer via dedicated exact/skip implementations

Rx.NET/Source/src/System.Reactive/Linq/Observable/Count.cs
No need to initialize the `_count` field to its default value.
=> 4.x: Count() don't init to default zero

Rx.NET/Source/src/System.Reactive/Linq/Observable/FirstAsync.cs
When `FirstAsync` finds an item, it disposes the upstream, however, the upstream may still emit an `OnCompleted` if it is unable to detect this dispose call (or ignores it). In this case, the `FirstAsync`'s `OnCompleted` gets invoked which creates an exception that gets thrown away as the base observer is already the no-op observer, wasting resources creating the stacktrace in the process. Both plain and predicated versions are affected.
I don't know how to verify this via unit test, but this extra call can be seen when placing a breakpoint in `FirstAsync`'s `OnCompleted` method and running this flow:
```cs
Observable.Return(1).FirstAsync().Subscribe();
```
=> 4.x: FirstAsync don't create exception after finding the item

Rx.NET/Source/src/System.Reactive/Linq/Observable/ForEach.cs
There is no need to initialize fields to their default values.
=> 4x: ForEach() don't init to default values

Rx.NET/Source/src/System.Reactive/Linq/Observable/Generate.cs
Inline the function callback fields into the sinks, remove init-to-default code, pass some parameters in calls instead of fields.
=> 4.x: Improve Generate() internals

Rx.NET/Source/src/System.Reactive/Linq/Observable/Collect.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Latest.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/MostRecent.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Next.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/PushToPullAdapter.cs
Inline the `SingleAssignmentDisposable` into the `PushPullSink` (similar to how `Sink`s were inlined).
This PR also includes the logic changes from #667 as the `Collect()` operator also uses the push-pull adapter.
=> 4.x: Improve PushPullAdapter+Sink dispose management

Rx.NET/Source/src/System.Reactive/Linq/Observable/Max.cs
There is no reason to initialize those fields to their default values.
=> 4.x: Max() don't init to default value

Rx.NET/Source/src/System.Reactive/Linq/Observable/Min.cs
There is no reason to initialize those fields to their default values.
=> 4.x: Min() don't initialize to default values

Rx.NET/Source/src/System.Reactive/Linq/Observable/Scan.cs
There is no need to initialize these fields to their default.
=> 4.x: Scan() don't init to default values

Rx.NET/Source/src/System.Reactive/Linq/Observable/Select.cs
There is no need to initialize the index field to its default value.
=> 4.x: indexed Select() don't init to default value

Rx.NET/Source/src/System.Reactive/Linq/Observable/SequenceEqual.cs
- Don't initialize fields to their default values
- Make the gate and queues read-only, initialize them in the constructor.
=> 4.x: SequenceEqual() initialization cleanup

Rx.NET/Source/src/System.Reactive/Linq/Observable/SingleAsync.cs
There is no reason to initialize the fields to their default values.
=> 4.x: SingleAsync() don't init to default values

Rx.NET/Source/src/System.Reactive/Linq/Observable/SkipUntil.cs
The `SkipUntilTerminalException` class was a remnant before the `ExceptionHelper` was introduced for the same and common functionality.
=> 4.x: SkipUntil() remove unused helper class

Rx.NET/Source/src/System.Reactive/Linq/Observable/Sum.cs
There is no reason to initialize the fields to their default values.
=> 4.x: Sum() don't init to default values

Rx.NET/Source/benchmarks/Benchmarks.System.Reactive/Program.cs, Rx.NET/Source/benchmarks/Benchmarks.System.Reactive/RangeBenchmark.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Range.cs, Rx.NET/Source/src/System.Reactive/Linq/QueryLanguage.Creation.cs
This PR improves the performance and reduces allocations in `Range()` as well as splits the operator to recursive and non-recursive variants due to a workaround required in the recursive version. See further explanations in the diff.
The PR also adds a benchmark for verifying the gains:
```
Intel Core i7-4790 CPU 3.60GHz (Haswell), 1 CPU, 8 logical and 4 physical cores
Frequency=3513586 Hz, Resolution=284.6095 ns, Timer=TSC
[Host]     : .NET Framework 4.6.2 (CLR 4.0.30319.42000), 64bit RyuJIT-v4.7.3110.0
DefaultJob : .NET Framework 4.6.2 (CLR 4.0.30319.42000), 64bit RyuJIT-v4.7.3110.0
// =============================
// Before
Method |       N |           Mean |         Error |        StdDev |      Gen 0 |   Allocated |
------- |-------- …
```
=> 4.x: Improve the performance of Range()

Rx.NET/Source/src/System.Reactive/Linq/Observable/Buffer.cs
Remove the `_index` field from the overlap-variant (accidentally left behind by some algorithm experimentation).
=> 4.x: Buffer(count, skip) remove unused _index field

Rx.NET/Source/src/System.Reactive/Linq/Observable/TakeLastBuffer.cs
- Pass the source and scheduler directly to `Run`
- Use `base.Run` to subscribe to the source.
=> 4.x: TakeLastBuffer() use base.Run, explicit args

Rx.NET/Source/src/System.Reactive/Linq/Observable/ToArray.cs
Once converted to an array, the list used for accumulating the items can be freed by GC. In addition, a failure should also free the list.
=> 4.x: ToArray() avoid retention of the list beyond the conversion

Rx.NET/Source/src/System.Reactive/Linq/Observable/DistinctUntilChanged.cs
There is no need to initialize fields to their default values.
=> 4.x: DistinctUntilChanged() don't init to default values

Rx.NET/Source/src/System.Reactive/Linq/Observable/Timer.cs
- Use a field `_index` to store the value to be emitted between schedule calls.
- Use stateful `Schedule` calls where appropriate.
=> 4.x: Improve Timer() scheduler handling

Rx.NET/Source/benchmarks/Benchmarks.System.Reactive/AppendPrependBenchmark.cs, Rx.NET/Source/benchmarks/Benchmarks.System.Reactive/Program.cs
Here is a benchmark for the append and prepend operators. The results on my slow machine:
``` ini
Intel Core i5-5200U CPU 2.20GHz (Broadwell), 1 CPU, 4 logical and 2 physical cores
Frequency=2143476 Hz, Resolution=466.5319 ns, Timer=TSC
[Host]     : .NET Framework 4.7.1 (CLR 4.0.30319.42000), 64bit RyuJIT-v4.7.3110.0
DefaultJob : .NET Framework 4.7.1 (CLR 4.0.30319.42000), 64bit RyuJIT-v4.7.3110.0
```
|              Method |     N |          Mean |       Error |      StdDev |        Median | Scaled | ScaledSD |     Gen 0 |    Gen 1 |   Gen 2 |  Allocated |
|-------------------- |------ |--------------:|------------:|------------:|--------------:|-------:|---------:|----------:|---------:|--------:|-----------:|
|      **StartWithArray** | …
=> Benchmark test for Append and Prepend

Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs
This will enable more usages of non-recursive scheduling. Before C# 7.3, the compiler will complain about some ambiguities, so we increase the language version.
=> Add non-recursive extensions for IScheduler allowing to return an IDisposable

Rx.NET/Source/benchmarks/Benchmarks.System.Reactive/Program.cs, Rx.NET/Source/benchmarks/Benchmarks.System.Reactive/RepeatBenchmark.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Repeat.cs, Rx.NET/Source/src/System.Reactive/Linq/QueryLanguage.Creation.cs
This PR improves the performance of `Repeat()` as well as reduces the allocations in it.
The changes are similar to #684:
- Split the implementation into recursive and long-running variants
- Use the sink fields to keep track of numbers
- Use direct task management for the recursive scheduling parts
Benchmark comparison:
```
Intel Core i7-4790 CPU 3.60GHz (Haswell), 1 CPU, 8 logical and 4 physical cores
Frequency=3513586 Hz, Resolution=284.6095 ns, Timer=TSC
[Host]     : .NET Framework 4.6.2 (CLR 4.0.30319.42000), 64bit RyuJIT-v4.7.3110.0
DefaultJob : .NET Framework 4.6.2 (CLR 4.0.30319.42000), 64bit RyuJIT-v4.7.3110.0
// =============================
// Before
Method |       N |             Mean |           Error |           StdDev | …
```
=> 4.x: Improve the performance of Repeat()

Rx.NET/Source/benchmarks/Benchmarks.System.Reactive/Program.cs, Rx.NET/Source/benchmarks/Benchmarks.System.Reactive/ToObservableBenchmark.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/ToObservable.cs, Rx.NET/Source/src/System.Reactive/Linq/QueryLanguage.Conversions.cs
This PR improves the performance and allocation behavior of the `ToObservable(IEnumerable)` operator by inlining the recursive scheduling management and splits the operator into separate, dedicated long-running and recursive variants.
The recursive variant is still declared to not link up the disposable management so the `volatile bool _disposed` field is enough to signal cancellation. In addition, the previous `Action<Action<>>`-based recursive scheduling was mostly responsible for the overhead as it was still tracking each recursively scheduled task despite they would have never gotten disposed.
Comparison:
```
Intel Core i7-4790 CPU 3.60GHz (Haswell), 1 CPU, 8 logical and 4 physical cores
Frequency=3513586 Hz, Resolution=284.6095 ns, …
```
=> 4.x: Improve the performance of ToObservable()

Rx.NET/Source/src/System.Reactive/Linq/Observable/AppendPrepend.cs, Rx.NET/Source/tests/Tests.System.Reactive/Tests/Linq/Observable/AppendPrependTest.cs
In the original code, calling `base.Dispose` disposed the `_upstream` as well so when the `_source` is subscribed to, it is immediately disposed and may never run or items may never appear downstream due to a detached observer. 
The PR removes this call and is safe because:
- if `_continue` is a `ForwardOnCompleted`, that calls `base.Dispose()` anyway
- if `_continue` is a `SubscribeSafe`, that is okay as `_scheduledDisposable` is just a `BooleanDisposable` and no other resources have to be disposed.
The `AppendPrepend_SchedulerLongRunning` verifies this scenario.
=> 4.x: Fix AppendPrepend disposing the main source on ILongRunningSchedulers

Rx.NET/Source/src/System.Reactive/Concurrency/NewThreadScheduler.cs, Rx.NET/Source/src/System.Reactive/Concurrency/TaskPoolScheduler.cs, Rx.NET/Source/src/System.Reactive/Concurrency/ThreadPoolScheduler.Windows.cs, Rx.NET/Source/src/System.Reactive/Concurrency/ThreadPoolScheduler.cs, Rx.NET/Source/src/System.Reactive/Internal/CurrentPlatformEnlightenmentProvider.cs
Currently the `ThreadPoolScheduler` uses `Instance` on `netstandard` and `Default` on UWP. This will lead to missing member exceptions if someone uses it from netstandard but runs on UWP since it won't be there.
This PR adds Instance to UWP and deprecates Default on UWP.
=> Use Instance as the name for UWP to match public netstandard surface area

Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Recursive.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/AppendPrepend.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Buffer.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Delay.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/DelaySubscription.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Empty.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/FromEvent.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/RefCount.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Skip.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/SkipUntil.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Take.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/TakeUntil.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Throttle.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Timeout.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Timer.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Window.cs, Rx.NET/Source/src/System.Reactive/Notification.cs, Rx.NET/Source/src/System.Reactive/ObservableBase.cs
In preparation for https://github.com/dotnet/reactive/pull/598, we evaluate where to replace IScheduler.Schedule by the ScheduleAction extension which does not allow recursive scheduling.
=> Make non-recursive schedulings explicit.

Rx.NET/Source/src/System.Reactive/Concurrency/LocalScheduler.TimerQueue.cs, Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Recursive.cs, Rx.NET/Source/src/System.Reactive/Concurrency/SchedulerWrapper.cs, Rx.NET/Source/src/System.Reactive/Internal/ConcatSink.cs, Rx.NET/Source/src/System.Reactive/Internal/TailRecursiveSink.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/CombineLatest.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Delay.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/DelaySubscription.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/FromEvent.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Max.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Min.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/PushToPullAdapter.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Timer.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Zip.cs, Rx.NET/Source/src/System.Reactive/Subjects/ReplaySubject.cs
No publicly visible classes were harmed in this PR.
=> Fix the constructor visibility of some abstract classes. 

.vsts.ix-shared.yml, Ix.NET/Source/Directory.build.props, Ix.NET/Source/Ix.NET.sln, Ix.NET/Source/System.Interactive/Skip.cs, Ix.NET/Source/System.Interactive/System.Interactive.csproj, Ix.NET/Source/System.Interactive/Take.cs, Ix.NET/Source/refs/System.Interactive/System.Interactive.csproj
This PR adds reference assemblies to Ix (not async).
This enables us to expose a lesser surface area to some tfm's, like `netcoreapp2.0` where they already have an `Enumerable.Take`.
The lib has the full impl, so people using it from a netstandard library won't be broken at runtime.
=> Ix Reference Assemblies

Rx.NET/Source/tests/Tests.System.Reactive/Tests/LicenseHeaderTest.cs
Ignore files with "\obj\" or "/obj/" in their pathname.
=> 4.x: License header check to ignore all \obj\ directories

Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs, Rx.NET/Source/tests/Tests.System.Reactive/Tests/Linq/Observable/ObserveOnTest.cs
This PR fixes the `StackOverflowException` when a long running `ObserveOn` (> 100.000 items) gets disposed due to the `ScheduledItem`s linked together when using the recursive scheduler.
The fix is to track the next recursive task's disposable directly and not allow the chaining to happen. For reference, this is the same effect that had to be considered in the improved `Range` and `ToObservable` implementations.
=> 4.x: Fix long sequence ObserveOn StackOverflowException upon Dispose

Rx.NET/Source/System.Reactive.sln, Rx.NET/Source/benchmarks/Benchmarks.System.Reactive/AppendPrependBenchmark.cs, Rx.NET/Source/benchmarks/Benchmarks.System.Reactive/Benchmarks.System.Reactive.csproj, Rx.NET/Source/benchmarks/Benchmarks.System.Reactive/Program.cs
This PR makes the referenced Rx-version switchable. It works by force-overriding the used Rx-version (if taken from nuget). It can be combined with the standalone solution from https://github.com/dotnet/reactive/pull/730, the solution should then have configurations that match the project configurations (current, Rx3.1.1, etc), so the config can easily be switched in the VS dropdown.
=> Enable switching Rx versions for benchmarks.

Rx.NET/Source/benchmarks/Benchmarks.System.Reactive/Benchmarks.System.Reactive.csproj, Rx.NET/Source/benchmarks/Benchmarks.System.Reactive/ComparisonAsyncBenchmark.cs, Rx.NET/Source/benchmarks/Benchmarks.System.Reactive/ComparisonBenchmark.cs, Rx.NET/Source/benchmarks/Benchmarks.System.Reactive/Program.cs
This PR adds a bunch of benchmark cases to be compared against v3.1.1 and v4.0.0 onc #731 is available to switch between versions.
I had to add `WindowsBase` and `System.Windows.Forms` otherwise using the `ObserveOn` and `SubscribeOn` operators complain about missing assemblies.
=> 4.x: Additional benchmarks for comparison

Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs
- Upgrade the `ObserveOnObserverNew` to be an `IdentitySink`
- Use the argument `q` inside `DrainStep`
- Document more explicitly why `DrainStep` uses an argument instead of the `_queue` field (to avoid re-reads mandated by the memory model, even though the field is readonly).
=> 4.x: Upgrade the ObserveOn operator to IdentitySink, fix queue usage

Ix.NET/Source/Benchmarks.System.Interactive/BenchmarkInterop.cs, Ix.NET/Source/Benchmarks.System.Interactive/Benchmarks.System.Interactive.csproj, Ix.NET/Source/Benchmarks.System.Interactive/BufferCountBenchmark.cs, Ix.NET/Source/Benchmarks.System.Interactive/Program.cs, Ix.NET/Source/Ix.NET.sln
This PR adds a subjproject to Ix.NET that allows running BenchmarkDotNet and enables validation for future improvements (for example, `EnumerableEx.Buffer` could be improved similarly to `Observable.Buffer`).
I've tried to add the configuration mechanism to allow comparing Ix 3.1.1 and the current sources but it didn't work. The configuration always reset to "Release" and running the program resulted in an unknown configuration error.
=> Ix: Add Benchmark subproject

Ix.NET/Source/Benchmarks.System.Interactive/DeferBenchmark.cs, Ix.NET/Source/Benchmarks.System.Interactive/Program.cs, Ix.NET/Source/System.Interactive/Defer.cs
This PR improves Ix `Defer` by removing the indirection and re-emission of the generated inner `IEnumerable` by simply returning its `IEnumerator`. I don't think the operator was intended to hide the actual objects nor is there any auto-detach behavior to consider like with `Observable.Defer`.
Comparison:
```
Frequency=3418037 Hz, Resolution=292.5656 ns, Timer=TSC
.NET Core SDK=2.1.301
[Host]     : .NET Core 2.1.1 (CoreCLR 4.6.26606.02, CoreFX 4.6.26606.05), 64bit RyuJIT
DefaultJob : .NET Core 2.1.1 (CoreCLR 4.6.26606.02, CoreFX 4.6.26606.05), 64bit RyuJIT
```
Method |       N |             Mean |          Error |         StdDev |  Gen 0| Allocated | …
=> Ix: Improve Defer() by removing indirection

Ix.NET/Source/Benchmarks.System.Interactive/BufferCountBenchmark.cs, Ix.NET/Source/System.Interactive/Buffer.cs
This PR improves the performance of the exact/skipping Ix `Buffer` operator by not using a queue just for a single buffer.
Comparison:
```
Frequency=3418037 Hz, Resolution=292.5656 ns, Timer=TSC
.NET Core SDK=2.1.301
[Host]     : .NET Core 2.1.1 (CoreCLR 4.6.26606.02, CoreFX 4.6.26606.05), 64bit RyuJIT
DefaultJob : .NET Core 2.1.1 (CoreCLR 4.6.26606.02, CoreFX 4.6.26606.05), 64bit RyuJIT
```
Method |       N |            Mean |          Error |         StdDev |      Gen 0 |  Allocated |
-------- |--------:|----------------:|---------------:|---------------:|-----------:|-----------:|
Exact |       1 |        191.1 ns |       1.489 ns |       1.244 ns | …
=> Ix: Improve the performance of Buffer exact/skip mode

Ix.NET/Source/Benchmarks.System.Interactive/IgnoreElementsBenchmark.cs, Ix.NET/Source/Benchmarks.System.Interactive/Program.cs, Ix.NET/Source/System.Interactive/IgnoreElements.cs
This PR reduces the overhead in Ix `IgnoreElements` by not doing a full `foreach` but only `MoveNext` on the upstream's `IEnumerator`.
```
Frequency=3418037 Hz, Resolution=292.5656 ns, Timer=TSC
.NET Core SDK=2.1.301
[Host]     : .NET Core 2.1.1 (CoreCLR 4.6.26606.02, CoreFX 4.6.26606.05), 64bit RyuJIT
DefaultJob : .NET Core 2.1.1 (CoreCLR 4.6.26606.02, CoreFX 4.6.26606.05), 64bit RyuJIT
```
Method |       N |            Mean |          Error |         StdDev |  Gen 0 | Allocated |
------- |--------:|----------------:|---------------:|---------------:|-------:|----------:|
Ignore |       1 |        50.70 ns |      0.4997 ns |      0.4674 ns | 0.0362 | …
=> Ix: Improve IgnoreElements() performance

Ix.NET/Source/Benchmarks.System.Interactive/MinMaxBenchmark.cs, Ix.NET/Source/Benchmarks.System.Interactive/Program.cs, Ix.NET/Source/System.Interactive/Max.cs, Ix.NET/Source/System.Interactive/Min.cs
They practically ran on the same underlying implementation.
- dedicated `Extrema` for min/max
- instead of potentially allocating a delegate, use the original `comparer` and use a +1/-1 valued argument to flip between the max/min mode.
```
Frequency=3418037 Hz, Resolution=292.5656 ns, Timer=TSC
.NET Core SDK=2.1.301
[Host]     : .NET Core 2.1.1 (CoreCLR 4.6.26606.02, CoreFX 4.6.26606.05), 64bit RyuJIT
DefaultJob : .NET Core 2.1.1 (CoreCLR 4.6.26606.02, CoreFX 4.6.26606.05), 64bit RyuJIT
```
Method |       N |             Mean |           Error |          StdDev |      Gen 0 |  Allocated |
------- …
=> Ix: Improve Min(), MinBy(), Max(), MaxBy() performance

Rx.NET/Source/src/System.Reactive/Linq/Observable/Latest.cs
There is an unused field in Latest that is only assigned to. On the other hand, access to the _value field happens once inside a lock and once outside. It's most probably a bug and the temporary variable should be used instead.
=> Fix Latest

Rx.NET/Source/src/System.Reactive/Threading/Tasks/TaskObservableExtensions.cs
According to https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs#L3611, the default-TaskScheduler is not TaskScheduler.Default but TaskScheduler.Current.
=> Fix for TaskObservableExtensions.Subscribe

Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Async.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Merge.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/SelectMany.cs, Rx.NET/Source/src/System.Reactive/Threading/Tasks/TaskObservableExtensions.cs
Some registration of continuations on tasks are possibly never unregistered, which may lead to memory leaks if the tasks are long lived. This PR attemps to fix this.
=> Avoid leaking task continuations

Rx.NET/Source/src/System.Reactive/Internal/Sink.cs
This is part of a a two part fix for #768. Dispose.Create has been inlined in 6ecc899a4ba35db5834f55dcfde019e19b431940, which, for RefCount, will lead to garbage if Sink.Dispose is called multiple times. This PR makes Sink.Dispose a nop from the second call on.
Note: This is not enough to fix #768, although the expectation of the OP about the behaviour is incorrect, there is another bug that will be fixed in a following PR.
=> Sink.Dispose should only call Dispose(true) once.

Rx.NET/Source/src/System.Reactive/Internal/Sink.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/RefCount.cs, Rx.NET/Source/tests/Tests.System.Reactive/Tests/Linq/Observable/RefCountTest.cs
This PR adds a dedicated connection state object to avoid reconnection and disconnection interference as well as some comments about what each part of the algorithm does.
(Note: it does not add the unit test from #773 as it is unclear to me that unit test is supposed to ensure, an old or new behavior?).
=> 4.x: Improve RefCount() internals

Rx.NET/Source/benchmarks/Benchmarks.System.Reactive/Program.cs, Rx.NET/Source/benchmarks/Benchmarks.System.Reactive/SubjectBenchmark.cs
This PR adds a benchmark to see the performance profile of `Subject` and provide a baseline to figure out where the additional overhead comes from compared to 3.1.1.
```
Intel Core i7-4790 CPU 3.60GHz (Haswell), 1 CPU, 8 logical and 4 physical cores
Frequency=3513590 Hz, Resolution=284.6092 ns, Timer=TSC
[Host]     : .NET Framework 4.6.2 (CLR 4.0.30319.42000), 64bit RyuJIT-v4.7.3110.0
DefaultJob : .NET Framework 4.6.2 (CLR 4.0.30319.42000), 64bit RyuJIT-v4.7.3110.0
```
Method |       N | M |             Mean |           Error |          StdDev |  Gen 0 | Allocated |
------------ |-------- |-- |-----------------:|----------------:|----------------:|-------:|----------:|
SubjectPush |       1 | 0 |         10.45 ns |       0.1207 ns | …
=> 4.x: Benchmark Subject

.vsts.ix-shared.yml, Ix.NET/Source/Directory.build.targets, Ix.NET/Source/Ix.NET.sln, Ix.NET/Source/System.Interactive.Providers/QueryableEx.cs, Ix.NET/Source/System.Interactive.Providers/System.Interactive.Providers.csproj, Ix.NET/Source/System.Interactive/Skip.cs, Ix.NET/Source/System.Interactive/System.Interactive.csproj, Ix.NET/Source/System.Interactive/Take.cs, Ix.NET/Source/global.json, Ix.NET/Source/refs/Directory.build.props, Ix.NET/Source/refs/System.Interactive.Providers.Ref/System.Interactive.Providers.Ref.csproj, Ix.NET/Source/refs/System.Interactive.Ref/System.Interactive.Ref.csproj
Remove custom code for reference assemblies in favor of the SDK Extras
=> Use Extras for ref assms

Rx.NET/Source/benchmarks/Benchmarks.System.Reactive/SubjectBenchmark.cs
This PR adds extra benchmarks to measure all 4 subject types with 7 lengths and 0-5 observers.
Raw measurement: [gist](https://gist.github.com/akarnokd/6dd2e87c0f998ac4978a4598442680ab).
=> 4.x: Expand Subjects benchmark

Rx.NET/Source/benchmarks/Benchmarks.System.Reactive/PrependVsStartWtihBenchmark.cs, Rx.NET/Source/benchmarks/Benchmarks.System.Reactive/Program.cs
Here is a benchmark test that compares the single item prepend and start with operator. I found the difference quite interesting. I did not expect the difference to be that enormous.
``` ini
Intel Core i5-5200U CPU 2.20GHz (Broadwell), 1 CPU, 4 logical and 2 physical cores
Frequency=2143476 Hz, Resolution=466.5319 ns, Timer=TSC
[Host]     : .NET Framework 4.7.1 (CLR 4.0.30319.42000), 64bit RyuJIT-v4.7.3110.0
DefaultJob : .NET Framework 4.7.1 (CLR 4.0.30319.42000), 64bit RyuJIT-v4.7.3110.0
```
|              Method |        Mean |     Error |    StdDev | Scaled | ScaledSD |  Gen 0 | Allocated |
|-------------------- |------------:|----------:|----------:|-------:|---------:|-------:|----------:|
|             Prepend |   706.17 ns |  9.443 ns …
=> Prepend vs StartWith benchmark

Rx.NET/Source/tests/Tests.System.Reactive/Tests/Concurrency/ThreadPoolSchedulerTest.cs
An equivalent test for DefaultScheduler is excluded already. The assertions made here is unjustifiable when tests are run in parallel and the ThreadPool is used by other concurrently running tests. An alternative would be to disable test parallelization completely.
=> Skip ThreadPoolSchedulerTest.No_ThreadPool_Starvation_Dispose on CI.

Rx.NET/Source/src/System.Reactive/Internal/Lookup.cs, Rx.NET/Source/tests/Tests.System.Reactive/Tests/Linq/Observable/ToLookupTest.cs
Instead of yielding the elements in a foreach loop, zero elements are skipped. Technically the result is the same with the benefit that the LINQ implementation can internally generate a type that keeps track of count of the enumerable. Consecutive operators can benefit from that knowledge.
=> Hide List<E> with .Skip(0)

Rx.NET/Source/src/System.Reactive/Internal/PriorityQueue.cs
The JIT does sometimes optimize tail recursion under some circumstances, but as far as I know, not always. Hence I would not rely on it and do the conversion by hand.
=> Remove tail recursion from the PriorityQueue

Rx.NET/Source/src/System.Reactive/Linq/Observable/Zip.cs, Rx.NET/Source/tests/Tests.System.Reactive/Tests/Linq/Observable/ZipTest.cs
If a source to the `Zip` operator completes immediately before the `SubscribeSafe` returned, the associated entry in `_subscriptions` would be still null, thus the `Dispose()` call fails with a `NullReferenceException`.
The fix checks if the `_subscriptions` is still valid and uses the deferred dispose approach to clean up the indexed entry.
=> Fix Zip(IEnumerable) NullReferenceException if a source completes immediately

Rx.NET/Source/Directory.build.targets, Rx.NET/Source/src/System.Reactive/Internal/HalfSerializer.cs
In case an upstream observable doesn't behave according to the protocol, the half-serializer will swallow values in ForwardOnNext. While the guidelines state that it is safe to assume that upstreams behave properly, this behaviour is different to <4.1.0 and it is fair to produce a warning.
=> Emit a warning if the half-serializer ignores a value in ForwardOnNext.

Rx.NET/Source/src/Microsoft.Reactive.Testing/TestScheduler.cs, Rx.NET/Source/src/System.Reactive/Concurrency/HistoricalScheduler.cs, Rx.NET/Source/tests/Tests.System.Reactive.ApiApprovals/Api/ApiApprovalTests.Core.approved.txt, Rx.NET/Source/tests/Tests.System.Reactive.ApiApprovals/Api/ApiApprovalTests.Testing.approved.txt
This is very helpful when debugging tests.
=> Added debugger display information to TestScheduler and HistoricalScheduler

Rx.NET/Source/src/System.Reactive/Linq/QueryLanguage.Creation.cs, Rx.NET/Source/tests/Tests.System.Reactive/Tests/Linq/Observable/CreateAsyncTest.cs
Before the accidental change, `Observable.Create(Func<IObserver<T>,[...], Task<IDisposable>)` and `Observable.Create(Func<IObserver<T>,[...], Task<Action>)` did not complete when the task body ended, unlike `Observable.Create(Func<IObserver<T>,[...],Task)`. 
There was an oversight when these operators have been upgraded and the plain `Task` version's logic was copy-pasted to them. Note though that there were no unit tests verifying the expected behavior at the time.
Fixes: #815
=> 4.x: Fix accidental behavior change with Task-based Create methods completing when the body ends

Rx.NET/Source/src/System.Reactive/Linq/Observable/Zip.cs, Rx.NET/Source/tests/Tests.System.Reactive/Tests/Linq/Observable/ZipTest.cs
This PR fixes the issue with the 3+ argument `Zip` operator not producing anything with an immediate `Observable.Return` source(s).
The problem was that the per-source `OnCompleted` called the `Dispose` method which then called the overridden `Dispose(bool)` method inside `ZipObservable` that cleared the queue, thus the operator could never make a full row. The fix is to call the original `Dispose(bool)` which only disposes the upstream but leaves the queue alone.
Fixes: #824
=> 4.x: Fix 3+ arg Zip not working with immediate sources

Rx.NET/Source/Directory.build.props, Rx.NET/Source/Directory.build.targets, Rx.NET/Source/System.Reactive.sln, Rx.NET/Source/global.json, Rx.NET/Source/src/Microsoft.Reactive.Testing/Microsoft.Reactive.Testing.csproj, Rx.NET/Source/src/System.Reactive/System.Reactive.csproj, Rx.NET/Source/tests/Tests.System.Reactive/DispatcherHelpers.cs, Rx.NET/Source/tests/Tests.System.Reactive/Tests.System.Reactive.csproj, Rx.NET/Source/tests/Tests.System.Reactive/Tests/Concurrency/SchedulerTest.cs, Rx.NET/Source/tests/Tests.System.Reactive/Tests/Linq/Observable/FromEventPatternTest.cs, Rx.NET/Source/tests/Tests.System.Reactive/Tests/Linq/Observable/ObserveOnTest.cs, Rx.NET/Source/tests/Tests.System.Reactive/Tests/Linq/Observable/SubscribeOnTest.cs, azure-pipelines.rx.yml
This is needed to provide DispatcherScheduler and ControlScheduler to WPF/WinForms on .NET Core 3.
As per @terrajobst, we should include these in the .NET Core 3 surface area even though these particular types are not implemented x-plat.
=> Add .NET Core 3 target

Rx.NET/Integration/IntegrationTests.sln, Rx.NET/Integration/LinuxTests.sln, Rx.NET/Integration/LinuxTests/LinuxTests.csproj, Rx.NET/Integration/LocalPackages/.keepme, Rx.NET/Integration/NuGet.Config, Rx.NET/Integration/WindowsDesktopTests/WindowsDesktopTests.csproj, Rx.NET/Integration/global.json, Rx.NET/Source/Directory.build.props, Rx.NET/Source/Directory.build.targets, Rx.NET/Source/global.json, Rx.NET/Source/src/System.Reactive/System.Reactive.csproj, Rx.NET/Source/src/System.Reactive/build/System.Reactive.targets, Rx.NET/Source/tests/Tests.System.Reactive.Uwp.DeviceRunner/Tests.System.Reactive.Uwp.DeviceRunner.csproj, azure-pipelines.rx.yml
Fixes #858, #864 
Adds integration tests for Linux and Windows Desktop to test the build targets.
Uses targets to determine what assembly gets referenced based on `UseWpf` or `UseWindowsForms` properties.
=> Handle Windows Desktop for .NET Core 3 in a way that works for Linux/non-Windows Desktop

Rx.NET/Source/src/System.Reactive/Concurrency/LocalScheduler.TimerQueue.cs, Rx.NET/Source/src/System.Reactive/Internal/SystemClock.cs, Rx.NET/Source/tests/Tests.System.Reactive/Tests/SystemClockTest.cs
When the clock change is notified, any modification to the SystemClockChanged hashset from the callbacks results in an InvalidOperationException. The fix is to create a copy of the hashset contents and enumerate that.
Resolves #879
=> 4.x: Fix InvalidOp when enumerating the SystemClockChanged hashset

Rx.NET/Source/src/System.Reactive/Concurrency/Synchronization.ObserveOn.cs, Rx.NET/Source/src/System.Reactive/Concurrency/Synchronization.cs, Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs, Rx.NET/Source/tests/Tests.System.Reactive/Tests/Linq/Observable/ObserveOnTest.cs
The optimized `ObserveOn` was using the `ISchedulerLongRunning` scheduler incorrectly. This type of scheduler is meant to be kept alive by possibly blocking the backing thread as long as the sequence is still active.
Additional changes:
- Removed the `ISchedulerLongRunning` cases from the `ObserveOnObserverNew` implementation.
- The `ObserveOnObserverNew` no longer supports error delaying (Based on unit tests, it was expected only from `ISchedulerLongRunning` schedulers anyway). 
- Created a new `ObserveOnObserverLongRunning` dedicated to working with `ISchedulerLongRunning`.
- The choice of which implementation to use has been moved to assembly time inside the `ObserveOn` extension method.
- Added unit test to verify there is no thread hopping with the TaskPoolScheduler.
- Added unit …
=> Fix wrong usage of ISchedulerLongRunning in ObserveOn

Ix.NET/Source/System.Linq.Async.Tests/System/Linq/Operators/OrderBy.cs, Ix.NET/Source/System.Linq.Async/System/Linq/Operators/OrderedAsyncEnumerable.cs
Also fixes https://github.com/dotnet/reactive/issues/886.
=> Use Array.Sort instead of QuickSort.

AsyncRx.NET/System.Reactive.Async.Linq/System/Reactive/Linq/Operators/Throttle.cs
Passes through `dueTime` parameter to the scheduler.
I verified this fixes the behaviour of the throttle operator [running the same test](https://github.com/dotnet/reactive/blob/ed1b84d8354a7778698dfc9da20cf6ed5ba9c93c/AsyncRx.NET/tests/Tests.System.Reactive.Async.Linq/ThrottleTests.cs) as in the Rx.NET codebase, via #896.
Resolves #808.
=> AsyncRx.NET: Fixes throttling by passing through dueTime to scheduler

Ix.NET/Source/System.Linq.Async/System/Linq/Operators/Intersect.cs, Ix.NET/Source/System.Linq.Async/System/Linq/Operators/Join.cs, Ix.NET/Source/System.Linq.Async/System/Linq/Operators/SelectMany.cs, Ix.NET/Source/System.Linq.Async/System/Linq/Operators/SequenceEqual.cs, Ix.NET/Source/System.Linq.Async/System/Linq/Operators/SkipWhile.cs, Ix.NET/Source/System.Linq.Async/System/Linq/Operators/TakeWhile.cs
Remove some unused `using` and use shadowing of local function parameters in one more case.
=> Some minor cleanup

Rx.NET/Source/src/System.Reactive/Linq/Observable/Finally.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Using.cs, Rx.NET/Source/tests/Tests.System.Reactive/Tests/Linq/Observable/FinallyTest.cs, Rx.NET/Source/tests/Tests.System.Reactive/Tests/Linq/Observable/UsingTest.cs, Rx.NET/Source/version.json
=> Cherry pick 832 to 41

Rx.NET/Source/src/System.Reactive/System.Reactive.csproj, Rx.NET/Source/src/System.Reactive/build/System.Reactive.targets
=> Don't emit framework reference on pack

Ix.NET/Source/Benchmarks.System.Interactive/BufferCountBenchmark.cs, Ix.NET/Source/Benchmarks.System.Interactive/IgnoreElementsBenchmark.cs, Ix.NET/Source/Benchmarks.System.Interactive/MinMaxBenchmark.cs, Ix.NET/Source/System.Interactive.Providers/System/Linq/QueryableEx.cs, Ix.NET/Source/System.Interactive/System/Linq/Operators/DistinctUntilChanged.cs, Ix.NET/Source/System.Interactive/System/Linq/Operators/Memoize.cs, Ix.NET/Source/System.Interactive/System/Linq/Operators/OnErrorResumeNext.cs, Ix.NET/Source/System.Interactive/System/Linq/Operators/Publish.cs, Ix.NET/Source/System.Interactive/System/Linq/Operators/Scan.cs, Ix.NET/Source/System.Interactive/System/Linq/Operators/Share.cs, Ix.NET/Source/System.Interactive/System/Linq/RefCountList.cs, Ix.NET/Source/System.Interactive/System/Linq/Yielder.cs, Ix.NET/Source/System.Linq.Async.Queryable/System/Linq/AsyncEnumerableRewriter.cs, Ix.NET/Source/System.Linq.Async.Tests/System/Linq/AsyncEnumerableNamingTests.cs, Ix.NET/Source/System.Linq.Async/System/Linq/Operators/SingleLinkedNode.cs
Deal with a few more cases. There still some warning behavior around `Debug.Assert` for down-level platforms (e.g. .NET 4.6.1) due to the lack of `[DoesNotReturnIf(false)]` on the `condition` parameter. My preference would be to suppress for down-level platforms that miss annotations.
=> Fix a few more nullability warnings

Rx.NET/Source/src/System.Reactive/Joins/Plan.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Aggregate.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Cast.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/CombineLatest.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Distinct.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/DistinctUntilChanged.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/FromEvent.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/FromEventPattern.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/GroupBy.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/GroupByUntil.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/GroupJoin.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Join.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/MaxBy.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/MinBy.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Select.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/SelectMany.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/WithLatestFrom.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Zip.cs, Rx.NET/Source/src/System.Reactive/Linq/QueryLanguage.Async.cs
Remove some remnants of an outdated coding style which gets in the way of nullability analysis.
=> Remove some uses of default(T)

Rx.NET/Source/src/System.Reactive/Concurrency/CurrentThreadScheduler.cs, Rx.NET/Source/src/System.Reactive/EventSource.cs, Rx.NET/Source/src/System.Reactive/Internal/ExceptionHelper.cs, Rx.NET/Source/src/System.Reactive/Internal/Helpers.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/AmbMany.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/AppendPrepend.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Case.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Contains.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/FromEvent.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/GroupBy.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/GroupByUntil.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/If.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Max.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Min.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/SelectMany.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/SequenceEqual.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Zip.cs, Rx.NET/Source/src/System.Reactive/Linq/QueryLanguage.Async.cs, Rx.NET/Source/src/System.Reactive/Subjects/AsyncSubject.cs, Rx.NET/Source/src/System.Reactive/Subjects/Subject.cs
Removing more cases where `default(T)` was used in conjunction with `var` to guide type inference, but it results in redundant assignments that can be removed.
=> Remove more redundant assignments

Rx.NET/Source/src/System.Reactive/Linq/Observable/Delay.cs, Rx.NET/Source/tests/Tests.System.Reactive/Tests/Linq/Observable/DelayTest.cs
The `_subscription` may be null if the participating Observables emit immediately and should have been disposed via the atomics utility method anyway.
Fixes #1048
=> Fix Delay(selector) NPE on immediate emissions

Rx.NET/Source/src/System.Reactive/Linq/Observable/Generate.cs, Rx.NET/Source/tests/Tests.System.Reactive/Tests/Linq/Observable/GenerateTest.cs
Due to how recursive scheduling has to link up `IDisposable`s in the [`UserWorkItem`](https://github.com/dotnet/reactive/blob/master/Rx.NET/Source/src/System.Reactive/Concurrency/UserWorkItem.cs#L29) class, a long running timed `Generate` would produce a long chain of `UserWorkItem`s and crash with stack overflow if the whole sequence itself is disposed.
The fix is to have the recursive scheduling in `Generate` not return the next step's `IDisposable` from the function but keep replacing a main reference with the newer and newer `IDisposable`s, and thus no link chain is formed.
The use of the SAD indirection is necessary because when the `Schedule` returns with the `IDisposable`, the payload may have already run and we would overwrite a newer step's `IDisposable`.
=> Fix Generate (timed) crash upon disposing a long sequence

Rx.NET/Source/src/System.Reactive/Concurrency/EventLoopScheduler.cs, Rx.NET/Source/tests/Tests.System.Reactive/Tests/Concurrency/EventLoopSchedulerTest.cs
=> Handle the case when EventLoopScheduler gets disposed with in-flight items

Rx.NET/Source/src/System.Reactive/Linq/Observable/Zip.cs, Rx.NET/Source/tests/Tests.System.Reactive/Tests/Linq/Observable/ZipTest.cs
`IEnumerator.Dispose` should not be called while `MoveNext` or `Current` is executing as most implementations don't expect a concurrent dispose call I think.
This PR adds a basic trampoline around the calls to `MoveNext` and `Current`. This allows a mutual exclusion between them and Dispose while also remembering `Dispose` should be eventually called:
1. The operator's Dispose is invoked and `_enumerationInProgress` atomically updates to 1: no concurrent MoveNext is happening and the enumerator can be disposed. If `OnNext` runs at this point `_enumerationInProgress` atomically updates to 2 and the method quits without doing anything.
2. `OnNext` atomically changes `_enumerationInProgress` to 1 and calls `MoveNext`. A concurrent `Dispose` on the operator now updates …
=> Serialize the dispose of Zip(IEnumerable) with MoveNext/Current

Ix.NET/Source/System.Interactive.Async/System/Linq/AsyncEnumerableEx.cs, Ix.NET/Source/System.Interactive.Async/System/Linq/Operators/Amb.cs, Ix.NET/Source/System.Interactive.Async/System/Linq/Operators/Buffer.cs, Ix.NET/Source/System.Interactive.Async/System/Linq/Operators/Catch.cs, Ix.NET/Source/System.Interactive.Async/System/Linq/Operators/Concat.cs, Ix.NET/Source/System.Interactive.Async/System/Linq/Operators/Defer.cs, Ix.NET/Source/System.Interactive.Async/System/Linq/Operators/Distinct.cs, Ix.NET/Source/System.Interactive.Async/System/Linq/Operators/DistinctUntilChanged.cs, Ix.NET/Source/System.Interactive.Async/System/Linq/Operators/Do.cs, Ix.NET/Source/System.Interactive.Async/System/Linq/Operators/Expand.cs, Ix.NET/Source/System.Interactive.Async/System/Linq/Operators/Finally.cs, Ix.NET/Source/System.Interactive.Async/System/Linq/Operators/Generate.cs, Ix.NET/Source/System.Interactive.Async/System/Linq/Operators/IgnoreElements.cs, Ix.NET/Source/System.Interactive.Async/System/Linq/Operators/IsEmpty.cs, Ix.NET/Source/System.Interactive.Async/System/Linq/Operators/Max.cs, Ix.NET/Source/System.Interactive.Async/System/Linq/Operators/MaxBy.cs, Ix.NET/Source/System.Interactive.Async/System/Linq/Operators/Merge.cs, Ix.NET/Source/System.Interactive.Async/System/Linq/Operators/Min.cs, Ix.NET/Source/System.Interactive.Async/System/Linq/Operators/MinBy.cs, Ix.NET/Source/System.Interactive.Async/System/Linq/Operators/Never.cs, Ix.NET/Source/System.Interactive.Async/System/Linq/Operators/OnErrorResumeNext.cs, Ix.NET/Source/System.Interactive.Async/System/Linq/Operators/Repeat.cs, Ix.NET/Source/System.Interactive.Async/System/Linq/Operators/Retry.cs, Ix.NET/Source/System.Interactive.Async/System/Linq/Operators/Return.cs, Ix.NET/Source/System.Interactive.Async/System/Linq/Operators/Scan.cs, Ix.NET/Source/System.Interactive.Async/System/Linq/Operators/SelectMany.cs, Ix.NET/Source/System.Interactive.Async/System/Linq/Operators/StartWith.cs, Ix.NET/Source/System.Interactive.Async/System/Linq/Operators/Throw.cs, Ix.NET/Source/System.Interactive.Async/System/Linq/Operators/Timeout.cs, Ix.NET/Source/System.Interactive.Async/System/Linq/Operators/Using.cs
Copied and adapted documentation from the equivalent `Observable` methods.
=> Document AsyncEnumerableEx methods

Rx.NET/Source/src/System.Reactive/Linq/Observable.Multiple.cs, Rx.NET/Source/src/System.Reactive/Linq/Qbservable.Generated.cs
> If a non-empty source completes, its very last value will be used for creating subsequent combinations until all sources terminate.
There is a comment in `Observable.Multiple.cs` implying a generator for `CombineLatest` but I couldn't find it: 
```cs
/* The following code is generated by a tool checked in to $/.../Source/Tools/CodeGenerators. */
```
Resolves #154
=> Indicate CombineLatest keeps using the very last value of a completed source

Rx.NET/Source/src/System.Reactive/Linq/IQueryLanguage.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable.Binding.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/RefCount.cs, Rx.NET/Source/src/System.Reactive/Linq/Qbservable.Generated.cs, Rx.NET/Source/src/System.Reactive/Linq/QueryLanguage.Binding.cs, Rx.NET/Source/tests/Tests.System.Reactive.ApiApprovals/Api/ApiApprovalTests.Core.approved.cs, Rx.NET/Source/tests/Tests.System.Reactive/Tests/Linq/Observable/RefCountTest.cs
This PR adds overloads to the `RefCount` operator that allows specifying the minimum number of observers to subscribe to it before the connection is established.
The change is trivial in the operator replacing the original constant representing one observer with an operator parameter.
```cs
var source = Observable.Range(1, 5).Publish().RefCount(2);
source.Subscribe(Console.WriteLine);
Console.WriteLine("No values should be printed yet");
source.Subscribe(Console.WriteLine);
```
prints
```
No values should be printed yet
1
1
2
2
3
3
4
4
5
5
```
Resolves #406
=> Add RefCount overloads with minimum observer count option

Rx.NET/Source/src/System.Reactive/Threading/Tasks/TaskObservableExtensions.cs, Rx.NET/Source/tests/Tests.System.Reactive.ApiApprovals/Api/ApiApprovalTests.Core.approved.cs, Rx.NET/Source/tests/Tests.System.Reactive/Tests/TaskObservableExtensionsTest.cs
This PR adds `IScheduler` overloads to the `ToTask` operator so that when the source terminates, the resumption is moved to the specified scheduler and performed there. 
This helps avoiding the case when the result of `ToTask` is awaited without capturing the current context or awaited in a way that blocks the resumption thread and thus the post-resumption actions inside `ToTask` can't run (i.e., disposing the upstream).
Resolves #838
=> Add ToTask overloads with IScheduler

Ix.NET/Source/System.Linq.Async/System/Linq/Operators/Average.Generated.cs, Ix.NET/Source/System.Linq.Async/System/Linq/Operators/Average.Generated.tt
In the generator for `Ix.Async.Average`, the word `nullable` was left in accidentally.
=> Fix Ix.Async.Average docs wording

Rx.NET/Source/src/Microsoft.Reactive.Testing/TestScheduler.cs, Rx.NET/Source/tests/Tests.System.Reactive/Tests/Concurrency/TestSchedulerTest.cs
There was an implied `created` <= `subscribed` <= `disposed` timing requirement in `TestScheduler.Start` that when not held, caused `NullReferenceException`. This PR adds parameter validation and documentation about this requirement.
Fixes #1114
=> Add more argument validation to TestScheduler.Start

Rx.NET/Source/src/System.Reactive/Concurrency/SynchronizationContextScheduler.cs
The infinitive generics recursion interacts poorly with AOT. The AOT compilers have hard figuring
out where the stop generating the code for generics with infinite recursion. They either fail or
produce large images by giving up once the generics get too complex.
This change reverts a small part of #500 that introduced infinite generic recursion and adds comment.
Fixes https://github.com/dotnet/corert/issues/7920
=> Avoid infinite generics recursion in SynchronizationContextScheduler

Rx.NET/Source/src/System.Reactive/Linq/Observable/Buffer.cs, Rx.NET/Source/tests/Tests.System.Reactive/Tests/Linq/Observable/BufferTest.cs
The queue in `Buffer.Timesliding._.Tick()` can become empty if the sequence terminates just before.
Fixes #1130.
=> Fix crash in Buffer due to empty queue in tick

Ix.NET/Source/System.Linq.Async.Tests/System/Linq/Operators/ToAsyncEnumerable.cs, Ix.NET/Source/System.Linq.Async/System/Linq/Operators/ToAsyncEnumerable.Observable.cs
Fixes #1157.
@akarnokd Not sure whether my proposed solution isn't already overkill. You are more experienced with lock free code.
I think it is safe to cancel a MoveNextAsync in-flight because it cancels the wait for an upstream notification. There is no work that in reality cannot be cancelled and would still go on.
=> Cancel in-flight TaskCompletionSources in ToAsyncEnumerable(Observable).

Ix.NET/Source/System.Linq.Async/System/Linq/AsyncEnumerable.AsyncOverloads.cs, Ix.NET/Source/System.Linq.Async/System/Linq/Operators/Max.cs, Ix.NET/Source/System.Linq.Async/System/Linq/Operators/OrderBy.cs
Good morning. I've added XML doc comments to the xxxAwaitAsync overloads in AsyncEnumerable.AsyncOverloads.cs in the Ix.Async.NET solution, as per [this issue](https://github.com/dotnet/reactive/issues/1097).
=> Added xml doc comments to overloads in AsyncEnumerable.AsyncOverloads.cs

Rx.NET/Source/global.json, azure-pipelines.rx.yml
A few generated files aren't properly included in the pdb. Fix should be in the 3.1.300 SDK.
=> use 3.1.300-preview to fix embedded pdb

Rx.NET/Source/src/System.Reactive/Concurrency/CatchScheduler.cs
Fix infinite recursive generics in CatchScheduler
Fixes #1133
=> Fix infinite recursive generics in CatchScheduler

Rx.NET/Source/src/System.Reactive/build/System.Reactive.targets
This PR adds a check to avoid adding a duplicate `FrameworkReference` item for `Microsoft.WindowsDesktop.App`, which caused the following warning:
> warning NETSDK1086: A FrameworkReference for 'Microsoft.WindowsDesktop.App' was included in the project. This is implicitly referenced by the .NET SDK and you do not typically need to reference it from your project. For more information, see https://aka.ms/sdkimplicitrefs
The item was duplicated as it had different metadata:
I'm not sure why that `FrameworkReference` item is needed (it was introduced in #1007), so there may be a better solution for this.
Fixes #1112
=> Don't add duplicate FrameworkReference

Rx.NET/Source/Directory.build.targets, Rx.NET/Source/src/System.Reactive/Internal/Constants.cs, Rx.NET/Source/src/System.Reactive/Internal/HalfSerializer.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable.Async.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable.Blocking.cs, Rx.NET/Source/src/System.Reactive/Linq/QueryLanguage.Imperative.cs, Rx.NET/Source/src/System.Reactive/Platforms/Desktop/Linq/Observable.Remoting.cs, Rx.NET/Source/src/System.Reactive/Platforms/Desktop/Linq/QueryLanguage.Remoting.cs, Rx.NET/Source/src/System.Reactive/Threading/Tasks/TaskObservableExtensions.cs, Rx.NET/Source/tests/Tests.System.Reactive/Tests/DefaultConcurrencyAbstractionLayerTest.cs, Rx.NET/Source/tests/Tests.System.Reactive/Tests/Linq/ObservableRemotingTest.cs, Rx.NET/Source/tests/Tests.System.Reactive/Tests/SystemClockTest.cs
Remove `#if` checks that are always true. Flip the `#if` checks to encode the exceptional case rather than the common case, thus reducing the number of `#define`s (e.g. `NO_TRACE` and `HAS_REMOTING` are the exceptions to the rule).
NB: For the time being, I'm leaving `HAS_WINRT` alone. I'll review these cases separately, because they're often combined with `CRIPPLED_REFLECTION` which also needs some closer look. If we can deprecate UAP 10.0 at some point, a lot more `#if` checks can go away.
NB: The `PREFER_ASYNC` stuff was used to control `[Obsolete]` attributes on various blocking members. I'll look into the steps towards final removal of these, given they've been marked as such for a long time (will review the history to make a call; alternatively, we can make the warning stronger and …
=> Reduce #if checks

Rx.NET/Source/src/System.Reactive/Internal/CurrentPlatformEnlightenmentProvider.cs, Rx.NET/Source/src/System.Reactive/Internal/ReflectionUtils.cs
Remove some more legacy stuff due to the `TypeInfo` split of the reflection APIs back in the WinRT days. More stuff to follow.
=> Reduce legacy reflection stuff

AsyncRx.NET/System.Reactive.Async.Linq/System/Reactive/Linq/Operators/FromEventPattern.cs
The `type` parameter should be used. Derivation of the type from an instance happens higher up.
=> Fix FromEventPatternCore's use of the type parameter.

AsyncRx.NET/System.Reactive.Async.Concurrency/System/Reactive/Concurrency/AsyncScheduler.cs, AsyncRx.NET/System.Reactive.Async.Concurrency/System/Reactive/Concurrency/AsyncSchedulerBase.cs, AsyncRx.NET/System.Reactive.Async.Concurrency/System/Reactive/Concurrency/ImmediateAsyncScheduler.cs, AsyncRx.NET/System.Reactive.Async.Concurrency/System/Reactive/Concurrency/SynchronizationContextAsyncScheduler.cs, AsyncRx.NET/System.Reactive.Async.Concurrency/System/Reactive/Concurrency/TaskPoolAsyncScheduler.cs, AsyncRx.NET/System.Reactive.Async.Interfaces/System/Reactive/Concurrency/IAsyncScheduler.cs, AsyncRx.NET/System.Reactive.Async.Linq/System/Runtime/CompilerServices/AsyncObservableMethodBuilder.cs, AsyncRx.NET/System.Reactive.Async.Subjects/System/Reactive/FastImmediateAsyncObserver.cs, AsyncRx.NET/System.Reactive.Async.Subjects/System/Reactive/ISchedulerAsyncObserver.cs, AsyncRx.NET/System.Reactive.Async.Subjects/System/Reactive/ScheduledAsyncObserver.cs, AsyncRx.NET/System.Reactive.Async.Subjects/System/Reactive/ScheduledAsyncObserverBase.cs, AsyncRx.NET/System.Reactive.Async.Subjects/System/Reactive/Subjects/ReplayAsyncSubject.cs, AsyncRx.NET/System.Reactive.Bcl/System/Threading/AsyncLock.cs
Further percolating the change of task types. Many scheduler (and associated) operations have a high likelihood of returning synchronously.
=> Use ValueTask on schedulers.

AsyncRx.NET/System.Reactive.Async.Disposables/System/Reactive/Disposables/CompositeAsyncDisposable.cs, AsyncRx.NET/System.Reactive.Async.Disposables/System/Reactive/Disposables/SerialAsyncDisposable.cs, AsyncRx.NET/System.Reactive.Async.Disposables/System/Reactive/Disposables/SingleAssignmentAsyncDisposable.cs, AsyncRx.NET/System.Reactive.Async.Linq/System/Reactive/Linq/Operators/Amb.cs, AsyncRx.NET/System.Reactive.Async.Linq/System/Reactive/Linq/Operators/CombineLatest.Generated.cs, AsyncRx.NET/System.Reactive.Async.Linq/System/Reactive/Linq/Operators/CombineLatest.Generated.tt, AsyncRx.NET/System.Reactive.Async.Linq/System/Reactive/Linq/Operators/Zip.Generated.cs, AsyncRx.NET/System.Reactive.Async.Linq/System/Reactive/Linq/Operators/Zip.Generated.tt, AsyncRx.NET/System.Reactive.Async.Subjects/System/Reactive/FastImmediateAsyncObserver.cs, AsyncRx.NET/System.Reactive.Async.Subjects/System/Reactive/ScheduledAsyncObserver.cs, AsyncRx.NET/System.Reactive.Async.Subjects/System/Reactive/ScheduledAsyncObserverBase.cs
Remove overload of `RendezVous` that uses a `Task`; all use cases are now `ValueTask`-based. Further switching disposables to use `ValueTask`. Further optimizations could follow in a few places.
=> Remove unnecessary rendez-vous based on Task.

Rx.NET/Source/src/System.Reactive/Linq/Observable.Async.cs
Fixed grammar mistake in `Observable.ForAsync` documentation. I was reading up about how the `ForAsync` works and I noticed a typo in the docs.
Some parts of the docs use the wording `Convert a X to an Y` while others use `Convert the X to an Y`, not quite sure which one is the wanted behavior here, I'm fine with the `an X to an Y`.
=> Fix Observable.FromAsync documentation grammar

Ix.NET/Source/System.Interactive.Async/System/Linq/Operators/Amb.cs, Ix.NET/Source/System.Interactive.Async/System/Linq/Operators/Buffer.cs, Ix.NET/Source/System.Interactive.Async/System/Linq/Operators/Catch.cs, Ix.NET/Source/System.Interactive.Async/System/Linq/Operators/Concat.cs, Ix.NET/Source/System.Interactive.Async/System/Linq/Operators/Defer.cs, Ix.NET/Source/System.Interactive.Async/System/Linq/Operators/DistinctUntilChanged.cs, Ix.NET/Source/System.Interactive.Async/System/Linq/Operators/Do.cs, Ix.NET/Source/System.Interactive.Async/System/Linq/Operators/Expand.cs, Ix.NET/Source/System.Interactive.Async/System/Linq/Operators/Finally.cs, Ix.NET/Source/System.Interactive.Async/System/Linq/Operators/Generate.cs, Ix.NET/Source/System.Interactive.Async/System/Linq/Operators/IgnoreElements.cs, Ix.NET/Source/System.Interactive.Async/System/Linq/Operators/Merge.cs, Ix.NET/Source/System.Interactive.Async/System/Linq/Operators/Repeat.cs, Ix.NET/Source/System.Interactive.Async/System/Linq/Operators/Scan.cs, Ix.NET/Source/System.Interactive.Async/System/Linq/Operators/Using.cs, Ix.NET/Source/System.Linq.Async/System/Linq/Operators/Cast.cs, Ix.NET/Source/System.Linq.Async/System/Linq/Operators/Except.cs, Ix.NET/Source/System.Linq.Async/System/Linq/Operators/GroupJoin.cs, Ix.NET/Source/System.Linq.Async/System/Linq/Operators/Intersect.cs, Ix.NET/Source/System.Linq.Async/System/Linq/Operators/Join.cs, Ix.NET/Source/System.Linq.Async/System/Linq/Operators/OfType.cs, Ix.NET/Source/System.Linq.Async/System/Linq/Operators/Select.cs, Ix.NET/Source/System.Linq.Async/System/Linq/Operators/SelectMany.cs, Ix.NET/Source/System.Linq.Async/System/Linq/Operators/SkipLast.cs, Ix.NET/Source/System.Linq.Async/System/Linq/Operators/SkipWhile.cs, Ix.NET/Source/System.Linq.Async/System/Linq/Operators/TakeLast.cs, Ix.NET/Source/System.Linq.Async/System/Linq/Operators/TakeWhile.cs, Ix.NET/Source/System.Linq.Async/System/Linq/Operators/Where.cs, Ix.NET/Source/System.Linq.Async/System/Linq/Operators/Zip.cs, Ix.NET/Source/System.Linq.Async/System/Runtime/CompilerServices/EnumeratorCancellationAttribute.cs
See:
* https://github.com/dotnet/csharplang/blob/master/meetings/2019/LDM-2019-04-15.md
* https://github.com/dotnet/csharplang/blob/master/meetings/2019/LDM-2019-04-29.md
* https://github.com/dotnet/standard/pull/1160
This PR adds the attribute for downlevel platforms, and leverages it for `IAsyncEnumerable<T>`-based iterators where the `Create(Core)` pattern using an `IAsyncEnumerator<T>`-based iterator has been used. The result will be reduction of allocations.
Goal is to ship with `HAS_ASYNC_ENUMERABLE_CANCELLATION` always set (and hence `#if` checks removed). Right now, the flag has to be set explicitly because we don't yet have a compiler drop that picks up on this attribute.
~~When we prepare for the final release in concert with C# 8.0 and .NET Core 3.0 shipping, we'll also revisit …
=> Initial work to support EnumeratorCancellation.

Ix.NET/Source/Directory.build.targets, Ix.NET/Source/System.Interactive.Async/System/Linq/Operators/Amb.cs, Ix.NET/Source/System.Interactive.Async/System/Linq/Operators/Buffer.cs, Ix.NET/Source/System.Interactive.Async/System/Linq/Operators/Catch.cs, Ix.NET/Source/System.Interactive.Async/System/Linq/Operators/Concat.cs, Ix.NET/Source/System.Interactive.Async/System/Linq/Operators/Defer.cs, Ix.NET/Source/System.Interactive.Async/System/Linq/Operators/DistinctUntilChanged.cs, Ix.NET/Source/System.Interactive.Async/System/Linq/Operators/Do.cs, Ix.NET/Source/System.Interactive.Async/System/Linq/Operators/Expand.cs, Ix.NET/Source/System.Interactive.Async/System/Linq/Operators/Finally.cs, Ix.NET/Source/System.Interactive.Async/System/Linq/Operators/Generate.cs, Ix.NET/Source/System.Interactive.Async/System/Linq/Operators/IgnoreElements.cs, Ix.NET/Source/System.Interactive.Async/System/Linq/Operators/Merge.cs, Ix.NET/Source/System.Interactive.Async/System/Linq/Operators/Repeat.cs, Ix.NET/Source/System.Interactive.Async/System/Linq/Operators/Scan.cs, Ix.NET/Source/System.Interactive.Async/System/Linq/Operators/Using.cs, Ix.NET/Source/System.Linq.Async/System/Linq/Operators/Cast.cs, Ix.NET/Source/System.Linq.Async/System/Linq/Operators/Except.cs, Ix.NET/Source/System.Linq.Async/System/Linq/Operators/GroupJoin.cs, Ix.NET/Source/System.Linq.Async/System/Linq/Operators/Intersect.cs, Ix.NET/Source/System.Linq.Async/System/Linq/Operators/Join.cs, Ix.NET/Source/System.Linq.Async/System/Linq/Operators/OfType.cs, Ix.NET/Source/System.Linq.Async/System/Linq/Operators/Select.cs, Ix.NET/Source/System.Linq.Async/System/Linq/Operators/SelectMany.cs, Ix.NET/Source/System.Linq.Async/System/Linq/Operators/SkipLast.cs, Ix.NET/Source/System.Linq.Async/System/Linq/Operators/SkipWhile.cs, Ix.NET/Source/System.Linq.Async/System/Linq/Operators/TakeLast.cs, Ix.NET/Source/System.Linq.Async/System/Linq/Operators/TakeWhile.cs, Ix.NET/Source/System.Linq.Async/System/Linq/Operators/Where.cs, Ix.NET/Source/System.Linq.Async/System/Linq/Operators/Zip.cs
Available on all platforms, so we no longer need to `#if` it out. Enable it everywhere, fix formatting, optimize in a few places.
=> Enable usage of EnumeratorCancellaton across the board.

Ix.NET/Source/System.Interactive.Async/System/Linq/Operators/Amb.cs, Ix.NET/Source/System.Interactive.Async/System/Linq/Operators/Catch.cs
Removes the last two uses of `Create` in favor of using iterators with cancellation support. Avoids delegate and anonymous enumerable object allocation.
=> Remove two more uses of AsyncEnumerable.Create.

Rx.NET/Source/src/System.Reactive/Linq/Observable/Aggregate.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Average.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/ElementAt.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/FirstAsync.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/LastAsync.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Max.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Min.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/SingleAsync.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/SingleOrDefaultAsync.cs, Rx.NET/Source/src/System.Reactive/Linq/QueryLanguage.Blocking.cs, Rx.NET/Source/src/System.Reactive/Threading/Tasks/TaskObservableExtensions.cs, Rx.NET/Source/tests/Tests.System.Reactive/Tests/Linq/Observable/SingleAsyncTest.cs
Improves https://github.com/dotnet/reactive/issues/1235 by ensuring there's a `StackTrace` for operators such as `SingleAsync` when propagating on `OnError` exception they've created themselves. Because there's no stack to unwind (`observer.OnError` goes "the other way"), the exception info is limited to the current frame (e.g. `OnCompleted` in `SingleAsync` noticing there was no element and thus propagating an `InvalidOperationException`). At the very least, it gives a clue about the operator that caused it. Further root cause analysis remains a debugging task (e.g. why the sequence produced no elements) but this can help to steer investigations.
=> Non-empty stack traces for operator exceptions.

Rx.NET/Source/tests/Tests.System.Reactive/Tests/Disposables/DisposableTests.cs, Rx.NET/Source/tests/Tests.System.Reactive/Tests/RegressionTest.cs
Remove unnecessary `#if` checks for types that are available across all target platforms currently.
=> Remove some NET45 and NET46 #if checks.

Rx.NET/Source/tests/Tests.System.Reactive/DispatcherHelpers.cs, Rx.NET/Source/tests/Tests.System.Reactive/Tests/Linq/Observable/ObserveOnTest.cs, Rx.NET/Source/tests/Tests.System.Reactive/Tests/Linq/Observable/SubscribeOnTest.cs
Weed out more legacy stuff to get a clear picture of all the feature flags `#if` checks we have left in the code.
=> Remove traces of Silverlight in #if checks

Rx.NET/Source/Directory.build.targets, Rx.NET/Source/benchmarks/Benchmarks.System.Reactive/Benchmarks.System.Reactive.csproj, Rx.NET/Source/facades/GlobalAssemblyVersion.cs, Rx.NET/Source/facades/System.Reactive.Core/System.Reactive.Core.csproj, Rx.NET/Source/facades/System.Reactive.Experimental/System.Reactive.Experimental.csproj, Rx.NET/Source/facades/System.Reactive.Interfaces/System.Reactive.Interfaces.csproj, Rx.NET/Source/facades/System.Reactive.Linq/System.Reactive.Linq.csproj, Rx.NET/Source/facades/System.Reactive.PlatformServices/System.Reactive.PlatformServices.csproj, Rx.NET/Source/facades/System.Reactive.Providers/System.Reactive.Providers.csproj, Rx.NET/Source/facades/System.Reactive.Runtime.Remoting/System.Reactive.Runtime.Remoting.csproj, Rx.NET/Source/facades/System.Reactive.Windows.Forms/System.Reactive.Windows.Forms.csproj, Rx.NET/Source/facades/System.Reactive.Windows.Threading/System.Reactive.Windows.Threading.csproj, Rx.NET/Source/src/Microsoft.Reactive.Testing/Microsoft.Reactive.Testing.csproj, Rx.NET/Source/src/System.Reactive.Observable.Aliases/System.Reactive.Observable.Aliases.csproj, Rx.NET/Source/src/System.Reactive/System.Reactive.csproj, Rx.NET/Source/tests/Directory.build.targets, Rx.NET/Source/tests/Tests.System.Reactive.ApiApprovals/Api/ApiApprovalTests.Aliases.verified.cs, Rx.NET/Source/tests/Tests.System.Reactive.ApiApprovals/Api/ApiApprovalTests.Core.verified.cs, Rx.NET/Source/tests/Tests.System.Reactive.ApiApprovals/Api/ApiApprovalTests.Testing.verified.cs, Rx.NET/Source/tests/Tests.System.Reactive/DispatcherHelpers.cs, Rx.NET/Source/tests/Tests.System.Reactive/Tests.System.Reactive.csproj, Rx.NET/Source/tests/Tests.System.Reactive/Tests/Concurrency/SchedulerTest.cs, Rx.NET/Source/tests/Tests.System.Reactive/Tests/Linq/Observable/FromEventPatternTest.cs
Upgrade to 4.7.2 as the minimum and remove `System.ValueTuple` package reference (see https://github.com/dotnet/reactive/issues/840).
=> Bump .NET Framework minimum version to v4.7.2.

Rx.NET/Source/src/System.Reactive/Linq/Observable/SelectMany.cs
This seems to go back all the way to https://github.com/dotnet/reactive/commit/e580d7ea9fca0a6bb89f4eb3c965377dfb252f0a. Exceptions should go out through `OnError`.
=> Propagate OverflowException in SelectMany via OnError.

Rx.NET/Source/src/System.Reactive/Concurrency/LocalScheduler.TimerQueue.cs, Rx.NET/Source/src/System.Reactive/Concurrency/Synchronization.Synchronize.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/All.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Any.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/AsObservable.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Contains.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Count.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/ForEach.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/IgnoreElements.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/IsEmpty.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/LongCount.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/OfType.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Sum.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Synchronize.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Timestamp.cs
Addressing some trivial operator implementations first before getting into schedulers and disposables which have non-trivial null behavior.
Progress to 0 suppressions: `195/337` left
=> More trivial nullable goodness.

Rx.NET/Source/src/System.Reactive/Internal/ExceptionServices.Default.cs, Rx.NET/Source/src/System.Reactive/Internal/ExceptionServices.cs, Rx.NET/Source/src/System.Reactive/Internal/ExceptionServicesImpl.cs, Rx.NET/Source/tests/Tests.System.Reactive.ApiApprovals/Api/ApiApprovalTests.Core.verified.cs
Helps with nullability tracking.
=> Mark exception throwing helpers as DoesNotReturn.

Rx.NET/Source/src/System.Reactive/Linq/Observable/Collect.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Latest.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/MostRecent.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Next.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/PushToPullAdapter.cs
Nullable checking for push-to-pull adapters.
=> Enable #nullable for push-pull adapters.

Rx.NET/Source/src/System.Reactive/Concurrency/ConcurrencyAbstractionLayerImpl.cs, Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Recursive.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/FromEvent.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Generate.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Range.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Repeat.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Return.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/SelectMany.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/TakeLast.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Throttle.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Throw.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Timeout.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Timer.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/ToObservable.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Window.cs
Mark some more lambdas as `static`.
=> More static lambdas in Rx.

Rx.NET/Source/src/System.Reactive/Disposables/Disposable.Utils.cs, Rx.NET/Source/src/System.Reactive/Disposables/Disposable.cs
First step towards being able to mark disposable stuff as `#nullable`.
=> Split public and internal disposable stuff.

Rx.NET/Source/src/System.Reactive/Linq/Observable/AppendPrepend.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Buffer.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Delay.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Merge.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Sample.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/SelectMany.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Switch.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Throttle.cs
Enabling for 8 more operators. Most notable suppressions with `!` are for the "if `hasValue` then use `value`" pattern.
Progress to 0 suppressions: `25/337` left
=> Enable #nullable for some more operators.

Rx.NET/Source/src/System.Reactive/Internal/Grouping.cs, Rx.NET/Source/src/System.Reactive/Internal/Map.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/GroupBy.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/GroupByUntil.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/GroupJoin.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Join.cs
Moving a little back and forth on these operators by cornering the `notnull` constraint suppression to separate files (`Map.cs`, `Lookup.cs`, `Grouping.cs`). We can later consider to absorb the `null` handling for these operators within these helpers, therefore encapsulating the `null`-checking logic that guards against passing a `null` key value to the underlying `[Concurrent]Dictionary<,>` instance.
=> Enable #nullable for Group/Join family of operators.

Rx.NET/Source/src/System.Reactive/Linq/Observable/Multicast.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/RefCount.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Window.cs
Just a few more operators to go. These do not have an impact on public API surface.
=> Enable #nullable for the last few operators.

Rx.NET/Source/src/System.Reactive/Disposables/CancellationDisposable.cs, Rx.NET/Source/src/System.Reactive/Disposables/ContextDisposable.cs, Rx.NET/Source/src/System.Reactive/Disposables/MultipleAssignmentDisposable.cs, Rx.NET/Source/src/System.Reactive/Disposables/RefCountDisposable.cs, Rx.NET/Source/src/System.Reactive/Disposables/ScheduledDisposable.cs, Rx.NET/Source/src/System.Reactive/Disposables/SerialDisposable.cs, Rx.NET/Source/src/System.Reactive/Disposables/SingleAssignmentDisposable.cs, Rx.NET/Source/tests/Tests.System.Reactive.ApiApprovals/Api/ApiApprovalTests.Core.verified.cs
First few `#nullable` introductions for disposable types. Note that `Disposable` properties on 3 of these types are now marked as `?` because they can return `null`.
More to come for the composite variants of disposables. The rub with all of these (and the query operators after inlining disposable logic everywhere) is that all the helper methods use `ref` parameters and often need to change to `IDisposable?` to be callable, but then the call site does not have a guarantee about assignment. So, for now, we're stuck with these helpers remaining null-oblivious.
=> Enable #nullable for some of the disposable types.

Rx.NET/Source/src/System.Reactive/Concurrency/ConcurrencyAbstractionLayerImpl.cs, Rx.NET/Source/src/System.Reactive/Disposables/ContextDisposable.cs, Rx.NET/Source/src/System.Reactive/Disposables/Disposable.Utils.cs, Rx.NET/Source/tests/Tests.System.Reactive/Tests/Disposables/DisposableTests.cs
Remove some helpers that are only used once. More `static` for lambdas. Less use of `object` where a strong type can be provided.
=> Clean up some code

Rx.NET/Source/tests/Tests.System.Reactive/DispatcherHelpers.cs, Rx.NET/Source/tests/Tests.System.Reactive/Tests/Concurrency/DispatcherSchedulerTest.cs, Rx.NET/Source/tests/Tests.System.Reactive/Tests/Linq/Observable/ObserveOnTest.cs, Rx.NET/Source/tests/Tests.System.Reactive/Tests/Linq/Observable/SubscribeOnTest.cs, Rx.NET/Source/tests/Tests.System.Reactive/WinFormsTestUtils.cs
These WinForms and WPF tests go all the way back to a private test infrastructure (prior to OSS) and later MsTest, and never were hardened against concurrent execution of test cases; they were always run sequentially. This has led to flakiness at some point later, maybe during the migration to Xunit, and it seems nobody ever addressed this.
This PR hardens things in a few ways:
* Ensure only one test for WinForms can run at a given point in time, to avoid multiple running UI threads. Same for WPF.
* Make tests hygienic, i.e. guarantee clean up of the thread they've spawn, and exiting the message loop (e.g. dispatcher).
* Avoid calling `Application.Exit` on a different thread.
* Simplify the way to write test code.
After this goes in, we can likely re-enable some tests that were disabled, …
=> Address flaky UI framework tests

Rx.NET/Source/src/System.Reactive/Internal/ImmutableList.cs
A lot of optimizations have gone into `Array.IndexOf`, so let's leverage this.
=> Use Array.IndexOf for better perf

Rx.NET/Source/src/Microsoft.Reactive.Testing/Microsoft.Reactive.Testing.csproj, Rx.NET/Source/tests/Tests.System.Reactive/Tests.System.Reactive.csproj
The `xunit.assert.source` NUGet package includes Xunit functionality as source code, which unfortunately has a bunch of code analysis warnings. Suppressing these warnings for the time being.
=> Suppress warnings in included Xunit source code

Rx.NET/Source/tests/Tests.System.Reactive/Tests/Concurrency/EventLoopSchedulerTest.cs, Rx.NET/Source/tests/Tests.System.Reactive/Tests/Linq/Observable/AppendPrependTest.cs, Rx.NET/Source/tests/Tests.System.Reactive/Tests/Linq/Observable/ObserveOnTest.cs
Noticed while debugging other test failures. Properly disposing these now.
=> Don't leak EventLoopScheduler instances in test code.

Rx.NET/Source/src/System.Reactive/Subjects/AsyncSubject.cs, Rx.NET/Source/src/System.Reactive/Subjects/BehaviorSubject.cs, Rx.NET/Source/src/System.Reactive/Subjects/ReplaySubject.cs, Rx.NET/Source/src/System.Reactive/Subjects/Subject.cs
Minor changes to make the inner disposable object similar across all subject types. In particular, make the `Dispose` call `null` out the fields for the observer and the parent subject, in case someone keeps these objects alive. So, we no longer keep the subject or observer alive by just a disposable. (Note that `Subject<T>` already did this.)
=> Make subject implementations a bit more alike.

Rx.NET/Source/src/System.Reactive/Subjects/AsyncSubject.cs, Rx.NET/Source/src/System.Reactive/Subjects/Subject.cs
A lot of logic in `Subject<T>` and `AsyncSubject<T>` is similar, so converge it again. This also saves on an allocation of a subscription object when trying to `Subscribe` to an already-completed `AsyncSubject<T>`. Furthermore, it uses `Array.IndexOf` rather than a manual loop, which has much better perf now (.NET Core optimizations).
=> Undo some code divergence.

Rx.NET/Source/src/System.Reactive/Disposables/Disposable.Utils.cs
One more bit of `#nullable` support. All of the helpers for `IDisposable` operations are rather gnarly given their excessive use of `ref` because of the underlying `Volatile` and `Interlocked` operations. Luckily we can flow nullable analysis through this using various attributes. In particular:
* read-only uses of `ref` (which could be `in` if the underlying APIs were to use `in`) can be annotated to ensure null-invariance;
* assignments through `ref` can be annotated to inherit their null-ness from the value being assigned.
=> Enable #nullable for disposable utils.

Rx.NET/Source/src/System.Reactive/Internal/ExceptionHelper.cs, Rx.NET/Source/tests/Tests.System.Reactive/Tests/Internal/ExceptionHelperTest.cs
Remove some code that's no longer used, and simplify the exception singleton used. It doesn't need to have a unique type (and we never perform type checks); we should just never leak the instance. Also addresses a few warnings:
```
src\System.Reactive\Internal\ExceptionHelper.cs(101,30): warning CA1032: Add the following constructor to TerminatedException: public TerminatedException(string message)
src\System.Reactive\Internal\ExceptionHelper.cs(101,30): warning CA1032: Add the following constructor to TerminatedException: public TerminatedException(string message, Exception innerException)
src\System.Reactive\Internal\ExceptionHelper.cs(101,30): warning CA1064: Exceptions should be public
```
=> Remove more dead code

Rx.NET/Source/src/System.Reactive/Internal/ExceptionServices.cs, Rx.NET/Source/src/System.Reactive/Internal/PushPullAdapter.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/GetEnumerator.cs, Rx.NET/Source/src/System.Reactive/Linq/QueryLanguage.Blocking.cs, Rx.NET/Source/src/System.Reactive/Runtime/CompilerServices/TaskObservableMethodBuilder.cs, Rx.NET/Source/src/System.Reactive/Subjects/AsyncSubject.cs, Rx.NET/Source/src/System.Reactive/Subjects/BehaviorSubject.cs
Code got into `BehaviorSubject<T>` that didn't leverage `IExceptionServices` to perform the rethrow. This mechanism was part of the `PlatformServices` separation and has also been used for hosting layers. Restore this for `BehaviorSubject<T>`.
Also simplifying all of the use sites of `ThrowIfNotNull` by using `?.` which works well with flow analysis and `#nullable` tracking (given the `DoesNotReturn` attribute on `Throw` and the lack of such an attribute that can make `ThrowIfNotNull` conditionally non-returning based on the nullability of the operand; `DoesNotReturnIf` only works with Boolean predicates).
=> Ensure all exception rethrows use EDI.

Rx.NET/Source/src/System.Reactive/Concurrency/EventLoopScheduler.cs, Rx.NET/Source/src/System.Reactive/Concurrency/Synchronization.cs, Rx.NET/Source/src/System.Reactive/Disposables/MultipleAssignmentDisposableValue.cs, Rx.NET/Source/src/System.Reactive/Disposables/SerialDisposableValue.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/AppendPrepend.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Catch.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Delay.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Range.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Repeat.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/TakeLast.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable/Timeout.cs
Contains previous unmerged work.
Introduces TrySetFirst methods on (Serial, Multiple)DisposableValue to make mixed usage scenarios possible.
What remains are usages that mostly observe the Try... return value or do custom Interlocked logic. This can possibly be mitigated too but it's not as mechanic as these previous changes.
GetValue - 1 reference (was 1)
GetValueOrDefault - 2 references (was 2)
SetSingle - no references (was none)
TrySetSingle - 6 references (was 19)
TrySetMultiple - 5 references (was 11)
TrySetSerial - 6 references (was 14)
GetIsDisposed - no references (was none )
Dispose - 12 references (was 25)
=> Even less Disposable.Utils

Rx.NET/Source/src/System.Reactive/Linq/Qbservable.Generated.cs, Rx.NET/Source/src/System.Reactive/Platforms/UWP/Linq/AsyncInfoObservable.cs
A whole slew of new warnings that came up after `Qbservable` code was converted to `#nullable enable`.
=> Fix a bunch of NRT warnings.

Rx.NET/Source/src/System.Reactive/System.Reactive.csproj, Rx.NET/Source/src/System.Reactive/build/System.Reactive.net5.0-windows.targets
When users target .net5-windows, they won't get the right assembly added. This change helps them realize that they need to target `net5.0-windows10.0.19041` by introducing a build error for anything between `[net5.0-windows..net5.0-windows10.0.19041[`.
Submitted by request from @clairernovotny
=> Add build error to help users know they need to retarget to 19041 when targeting net5.0-windows

Ix.NET/Source/System.Linq.Async.Tests/System/Linq/Operators/OfType.cs, Ix.NET/Source/System.Linq.Async/System/Linq/Operators/OfType.cs
When using `OfType<T>` on an `IAsyncEnumerable<T?>` the compiler raised CS8620 warning:
```
Argument of type 'IAsyncEnumerable<object?>' cannot be used for parameter 'source' of type 'IAsyncEnumerable<object>'
in 'IAsyncEnumerable<object> AsyncEnumerable.OfType<object>(IAsyncEnumerable<object> source)'
due to differences in the nullability of reference types.
```
The warning appeared in the unit test I've added, before I've changed `OfType` declaration.
The expected behavior is that the compiler doesn't raise a warning, because we're explicitly asking for our collection to be filtered for not-null objects (null has no type in terms of type checks).
The fix is to change the nullability of type parameter for extension method receiver (`this …
=> fix: OfType now accepts a collection of object?

Ix.NET/Source/ApiCompare/ApiCompare.csproj, Ix.NET/Source/FasterLinq/FasterLinq.csproj, Ix.NET/Source/Playground/Playground.csproj, Ix.NET/Source/System.Interactive.Async.Providers.Tests/System.Interactive.Async.Providers.Tests.csproj, Ix.NET/Source/System.Interactive.Async.Tests/System.Interactive.Async.Tests.csproj, Ix.NET/Source/System.Interactive.Providers/System.Interactive.Providers.csproj, Ix.NET/Source/System.Interactive.Tests/System.Interactive.Tests.csproj, Ix.NET/Source/System.Interactive.Tests/System/Linq/Operators/Max.cs, Ix.NET/Source/System.Interactive.Tests/System/Linq/Operators/MaxBy.cs, Ix.NET/Source/System.Interactive.Tests/System/Linq/Operators/Min.cs, Ix.NET/Source/System.Interactive.Tests/System/Linq/Operators/MinBy.cs, Ix.NET/Source/System.Interactive.Tests/System/Linq/Operators/SkipLast.cs, Ix.NET/Source/System.Interactive.Tests/System/Linq/Operators/TakeLast.cs, Ix.NET/Source/System.Interactive/System.Interactive.csproj, Ix.NET/Source/System.Interactive/System/Linq/Operators/Max.cs, Ix.NET/Source/System.Interactive/System/Linq/Operators/MaxBy.cs, Ix.NET/Source/System.Interactive/System/Linq/Operators/Min.cs, Ix.NET/Source/System.Interactive/System/Linq/Operators/MinBy.cs, Ix.NET/Source/System.Interactive/System/Linq/Operators/SkipLast.cs, Ix.NET/Source/System.Interactive/System/Linq/Operators/TakeLast.cs, Ix.NET/Source/System.Linq.Async.Queryable.Tests/System.Linq.Async.Queryable.Tests.csproj, Ix.NET/Source/System.Linq.Async.Tests/System.Linq.Async.Tests.csproj, Ix.NET/Source/refs/System.Interactive.Providers.Ref/System.Interactive.Providers.Ref.csproj, Ix.NET/Source/refs/System.Interactive.Ref/System.Interactive.Ref.csproj, Ix.NET/Source/refs/System.Linq.Async.Ref/System.Linq.Async.Ref.csproj, Ix.NET/Source/version.json, azure-pipelines.ix.yml
Hello and thank you for contributing to dotnet/reactive. Before you proceed by creating a pull request (PR):
> Please make sure your contribution is in line with the project's [licensing model](https://github.com/dotnet/reactive/blob/master/LICENSE) and
your employment allows you to contribute to open source.
> Please sign the [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/reactive?pullRequest=1101) in case the CLA bot asks you
for being a new contributor.
> Please make sure you target the `master` branch when creating the PR.
> Please describe what and how the bug manifested itself and what kind of fix did you implement.
> Practically, you are writing these descriptions for the search engines so others can find the …
=> Update to 6.0 SDK and exclude min/max/minby/maxby from 6.0 refs

Ix.NET/Source/System.Interactive/System/Linq/Operators/Max.cs, Ix.NET/Source/System.Interactive/System/Linq/Operators/MaxBy.cs, Ix.NET/Source/System.Interactive/System/Linq/Operators/Min.cs, Ix.NET/Source/System.Interactive/System/Linq/Operators/MinBy.cs, Ix.NET/Source/System.Interactive/System/Linq/Operators/SkipLast.cs, Ix.NET/Source/System.Interactive/System/Linq/Operators/TakeLast.cs, Ix.NET/Source/System.Linq.Async.SourceGenerator/System.Linq.Async.SourceGenerator.csproj
Uses a fixed Extras that enables the OR_GREATER defines
=> Fix defines to be OR_GREATER

Ix.NET/Source/System.Interactive.Providers/System/Linq/QueryableEx.Generated.cs, Ix.NET/Source/System.Interactive.Tests/System.Interactive.Tests.csproj, Ix.NET/Source/System.Interactive/System/Linq/Operators/Max.cs, Ix.NET/Source/System.Interactive/System/Linq/Operators/MaxByWithTies.cs, Ix.NET/Source/System.Interactive/System/Linq/Operators/Min.cs, Ix.NET/Source/System.Interactive/System/Linq/Operators/MinBy.cs, Ix.NET/Source/System.Interactive/System/Linq/Operators/MinByWithTies.cs
Follow-up from #1647 so we don't lose functionality even if we have to rename due to overload resolution rules.
=> Add MinByWithTies and MaxByWithTies to bring back a MinBy/MaxBy that returns a list

Rx.NET/Documentation/adr/0002-versioning-policy.md, Rx.NET/Source/version.json
This defines our Rx versioning policy for versions after v5.0, and also updates the version configuration accordingly.
=> Set Rx vnext to 6.0 and add versioning ADR

AsyncRx.NET/ApiCompare/ApiCompare.csproj, AsyncRx.NET/Directory.build.props, AsyncRx.NET/Playground/Playground.csproj, AsyncRx.NET/build/signclient.json, AsyncRx.NET/version.json, azure-pipelines.asyncrx.yml
This is a prerequisite for being able to publish AsyncRx.NET packages to NuGet.
=> Add AsyncRx.NET build pipeline

Rx.NET/Source/src/System.Reactive/System.Reactive.csproj, Rx.NET/Source/src/System.Reactive/build/System.Reactive.net6.0-windows.targets
Resolves #1893. Resolves #1889
PR #1449 seems to cause more problems than it solves - see #1893
Once we separate the UI frameworks back out into their own packages, the issue that PR was intended to solve will go away in any case.
=> Back out #1449

Rx.NET/Source/Directory.build.targets, Rx.NET/Source/src/System.Reactive/Internal/Constants.cs, Rx.NET/Source/src/System.Reactive/Internal/ReflectionUtils.cs, Rx.NET/Source/src/System.Reactive/Linq/IQueryLanguage.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable.Events.cs, Rx.NET/Source/src/System.Reactive/Linq/Observable.Queryable.cs, Rx.NET/Source/src/System.Reactive/Linq/Qbservable.Joins.cs, Rx.NET/Source/src/System.Reactive/Linq/Qbservable.cs, Rx.NET/Source/src/System.Reactive/Linq/QbservableEx.NAry.cs, Rx.NET/Source/src/System.Reactive/Linq/QueryLanguage.Events.cs, Rx.NET/Source/src/System.Reactive/ObservableQuery.cs, Rx.NET/Source/src/System.Reactive/Platforms/Desktop/Linq/Observable.Remoting.cs, Rx.NET/Source/src/System.Reactive/System.Reactive.csproj, Rx.NET/Source/tests/Tests.System.Reactive.Uwp.DeviceRunner/Tests.System.Reactive.Uwp.DeviceRunner.csproj
Resolves #1683 
Note that most of the query-space features (`IQbservable` etc.) do not mix well with trimming, so these are annotated as requiring external code.
Also, although the trimming attributes do provide a way to declare that a type's public events will be used, the way in which the reflection-driven `FromEvent` code paths invoke delegates seems to be something that the trimmability analyzers can't understand. So these members are also annotated as being problematic for trimming.
=> Enable trimming in .NET 6 targets

README.md
Dead link checker help you to avoid such issues
Hello and thank you for contributing to dotnet/reactive. Before you proceed by creating a pull request (PR):
> Please make sure your contribution is in line with the project's [licensing model](https://github.com/dotnet/reactive/blob/main/LICENSE) and
your employment allows you to contribute to open source.
> Please sign the [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/reactive?pullRequest=1101) in case the CLA bot asks you
for being a new contributor.
> Please make sure you target the `main` branch when creating the PR.
> Please describe what and how the bug manifested itself and what kind of fix did you implement.
> Practically, you are writing these descriptions for the …
=> remove broken link (ruby implementation)

Rx.NET/Source/src/System.Reactive/Disposables/SingleAssignmentDisposableValue.cs, Rx.NET/Source/tests/Tests.System.Reactive.ApiApprovals/Api/ApiApprovalTests.Core.verified.cs
When implementing various things outside of this library like a custom IScheduler or a custom rx operator the _SingleAssignmentDisposableValue_ can be quite useful. Since it is already well documented and it seams to me like it can't be used wrong, I'd like to make it public and make implement _ICancelable_ also.
Would that be ok with you?
Also please let me know if I have to bump versions manually.
=> exposing SingleAssignmentDisposableValue and making it ICancelable

Rx.NET/Source/Directory.build.props, Rx.NET/Source/benchmarks/Benchmarks.System.Reactive/Benchmarks.System.Reactive.csproj, Rx.NET/Source/tests/Tests.System.Reactive.ApiApprovals/Tests.System.Reactive.ApiApprovals.csproj
* Nerdbank.GitVersioning 3.6.128
* BenchmarkDotNet 0.13.5
* Verify.Xunit 19.14.1
Also disabled Nerdbank.GitVersioning for UWP test runner since recent versions of this library import a .proj file that doesn't work with UWP projects. (The runner doesn't need to be built with the current version number, since we never publish it anyway.)
Resolves #1898
=> Update NuGet refs

Rx.NET/Documentation/ReleaseHistory/Rx.v6.md
The breaking changes didn't previous mention that v6 raises the lower bound on the target platform version when targeting UWP. 
This change was described in https://github.com/dotnet/reactive/blob/main/Rx.NET/Documentation/adr/0001-net7.0-era-tooling-update.md#windows-sdk-version-1
=> Mention change in min UWP target platform version in release notes

AsyncRx.NET/ApiCompare/ApiCompare.csproj, AsyncRx.NET/System.Reactive.Async/Linq/Operators/CombineLatest.Generated.tt, AsyncRx.NET/System.Reactive.Async/Linq/Operators/Zip.Generated.tt, AsyncRx.NET/System.Reactive.Async/System.Reactive.Async.csproj
Resolves #1954 
**NOTE**: it is not yet clear whether this is going to work, because we don't currently know why the project didn't do this to begin with.
It's true that `netstandard2.0` doesn't include the `IAsyncEnumerable<T>`, `IAsyncEnumerator<T>`, and `IAsyncDisposable` interfaces, but these are available through the `Microsoft.Bcl.AsyncInterfaces` NuGet package. Perhaps that wasn't available when this code was first written. But there might be some deeper problem. (And since this project doesn't yet have a test suite, we can't be confident in changes like this.)
If @bartdesmet happens to spot this, it would be great to know whether there's some good reason we can't just use that NuGet package to get ourselves a `netstandard2.0`-compatible package.
So this is currently an …
=> Add netstandard2.0 target to AsyncRx.NET

Rx.NET/Documentation/ReleaseHistory/Rx.v6.md, Rx.NET/Source/src/System.Reactive/Internal/CurrentPlatformEnlightenmentProvider.cs, Rx.NET/Source/version.json
(Just use new() instead.)
Resolves #1942
This dynamic load has been unnecessary since commit 40e8696 modified CurrentPlatformEnlightenmentProvider to look for QueryDebugger in the assembly named System.Reactive. Before that, it used to look for one called System.Reactive.Debugger, in which case a dynamic load would have made sense. But since for almost 6 years now, it has been passing "System.Reactive" as the assembly name, there is absolutely no reason for this to be a dynamic load. The code that performs this dynamic load is also in System.Reactive, so the dynamic load is completely pointless.
This only ever happened when the debugger was attached, but it has become problematic because assembly trimming doesn't like dynamic loads. If you set <PublishAot>true</PublishAot>, this dynamic …
=> Remove dynamic load of QueryDebugger

AsyncRx.NET/System.Reactive.Async/Linq/Operators/Defer.cs
Resolves #1976 
The `DeferAsync` methods are meant to just call into the equivalent `Defer` methods. (I don't know the history behind why we have both, but I'm guessing that DeferAsync might be useful in cases where you want the compiler to infer the delegate type. With just Defer, it might be unclear whether you mean the one where the factory returns an observable, or the one where the factory returns a value task that produces an observable.)
This looks like a simple coding error: one of the `DeferAsync` overloads calls itself. (This is why we need #1900 - this would have been caught if this project had tests.)
=> Fix AsyncObservable.DeferAsync infinite recursion

AsyncRx.NET/System.Reactive.Async/Linq/Operators/ForEachAsync.cs
Resolves #1940
The code that waits for processing to complete was after the closing brace of the `using` that unregisters the cancellation callback. This meant that it almost immediately unregistered for cancellation notifications. Simply moving that await inside the relevant block addresses this.
=> Retain cancel callback until ForEachAsync completes

Ix.NET/Source/System.Linq.Async/System.Linq.Async.csproj
Update `System.Linq.Async` dependency condition for `Microsoft.Bcl.AsyncInterfaces`
=> Avoid spurious references to Microsoft.Bcl.AsyncInterfaces

Rx.NET/Source/tests/Tests.System.Reactive/Tests/TaskLikeSupportTest.cs
It turns out that occasionally, the test thread ends up with its SynchronizationContext.Current set to the Windows Forms sync context. That's bad because nothing runs a message loop, so when AsyncSubject attempts to complete an awaited operation, it tries to do so by posting a message to a queue that's never going to be processed.
So we explicitly set the context to null for the test that expects that.
Relates to (but doesn't fully deal with) #1885
=> Clear sync context on test that requires it to be absent

Rx.NET/Integration/LinuxTests/LinuxTests.csproj, Rx.NET/Integration/WindowsDesktopTests/WindowsDesktopTests.csproj, Rx.NET/Source/Directory.build.targets, Rx.NET/Source/tests/Tests.System.Reactive/Tests.System.Reactive.csproj, Rx.NET/Source/tests/Tests.System.Reactive/Tests/Linq/Observable/ToLookupTest.cs, azure-pipelines.rx.yml
Added `net8.0` and `net8.0-windows10.0.19041` targets to test project.
Modified `Directory.build.targets` to recognize .NET 8.0 targets.
One test needed to be lightly modified because the way in which it was trying to test what it wanted to test doesn't quite work in .NET 8.0.
=> Run tests on .NET 8.0

Rx.NET/Documentation/IntroToRx/01_WhyRx.md
Hello and thank you for contributing to dotnet/reactive. Before you proceed by creating a pull request (PR):
> Please make sure your contribution is in line with the project's [licensing model](https://github.com/dotnet/reactive/blob/main/LICENSE) and
your employment allows you to contribute to open source.
> Please sign the [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/reactive?pullRequest=1101) in case the CLA bot asks you
for being a new contributor.
> Please make sure you target the `main` branch when creating the PR.
> Please describe what and how the bug manifested itself and what kind of fix did you implement.
> Practically, you are writing these descriptions for the search engines so others can find the resolution …
=> Fix typo in 01_WhyRx.md

azure-pipelines.asyncrx.yml, azure-pipelines.ix.yml, azure-pipelines.rx.yml
The old `signtool` has been retired. This moves over to the new [`sign`](https://github.com/dotnet/sign) tool.
This offers two significant security improvements:
1. we can use a Managed Identity instead of the old [client credentials flow](https://learn.microsoft.com/en-us/entra/identity-platform/v2-oauth2-client-creds-grant-flow) to authenticate with Azure Key Vault
2. the critical cryptographic step now happens inside Azure Key Vault, not on the build agent
Both of these improvements remove the need for the build agent to be in possession of a critical secret.
Because of 1, we no longer need to supply the build agent with a Client Secret. That Client Secret was critical because if it had ever been leaked, they would effectively have stolen the build agent's identity, and would have been …
=> Use new sign tool

Rx.NET/Documentation/IntroToRx/D_AlgebraicUnderpinnings.md
See https://github.com/dotnet/reactive/issues/2184
=> Suggested fixes for Issue #2184

Ix.NET/Source/Ix.NET.sln, Ix.NET/Source/NetCore31TestReadme.txt, Ix.NET/Source/NetStandard21TestReadme.txt, Ix.NET/Source/System.Interactive.Async.Providers.Tests/System.Interactive.Async.Providers.Tests.csproj, Ix.NET/Source/System.Interactive.Async.Tests/System.Interactive.Async.Tests.csproj, Ix.NET/Source/System.Interactive.Async.Tests/System/Linq/Operators/Distinct.cs, Ix.NET/Source/System.Interactive.Tests/System.Interactive.Tests.csproj, Ix.NET/Source/System.Linq.Async.Queryable.Tests/System.Linq.Async.Queryable.Tests.csproj, Ix.NET/Source/System.Linq.Async.Tests/System.Linq.Async.Tests.csproj, Ix.NET/Source/System.Linq.Async.Tests/System/Linq/Operators/Concat.cs, Ix.NET/Source/System.Linq.Async.Tests/System/Linq/Operators/DefaultIfEmpty.cs, Ix.NET/Source/System.Linq.Async.Tests/System/Linq/Operators/Distinct.cs, Ix.NET/Source/System.Linq.Async.Tests/System/Linq/Operators/OrderBy.Generated.cs, azure-pipelines.ix.yml
Azure DevOps Hosted Build Agents now run Ubuntu 24. One consequence is that mono is no longer available on the build agents—it is not supported on Ubuntu 24.
The Ix pipeline had been running on Ubuntu, which meant that the unit tests targetting .NET FX relied on mono. We can't do that any more. This PR changes the build agent back to Windows, so we can continue to test on .NET FX.
Also, the tests were crashing on .NET Core 3.1. That runtime has been out of support for a long time, but we had continued to use it as it was the only way to test our `netstandard2.1` support. I've had to disable this, so for now we don't execute tests against the `netstandard2.1` builds. It's possible that there's no longer any reason to offer this target, so we might need to remove that in the future.
There's …
=> Fix Ix.NET build break on Ubuntu 24

Rx.NET/Documentation/ReleaseHistory/Rx.v6.md, Rx.NET/Integration/LinuxTests/LinuxTests.csproj, Rx.NET/Integration/WindowsDesktopTests/WindowsDesktopTests.csproj, Rx.NET/Integration/global.json, Rx.NET/Source/Directory.build.props, Rx.NET/Source/src/System.Reactive/Linq/Observable/RefCount.cs, Rx.NET/Source/tests/Tests.System.Reactive/Tests.System.Reactive.csproj, Rx.NET/Source/tests/Tests.System.Reactive/Tests/Linq/Observable/RefCountTest.cs, Rx.NET/Source/tests/Tests.System.Reactive/Tests/MySubject.cs, Rx.NET/Source/version.json, azure-pipelines.rx.yml
Resolves #2173, resolves #2214, resolves #2215
Adds more `RefCount` unit tests.
`RefCount` has two implementations: the `Eager` one, which disconnects the instant the subscriber count drops to 0, and the `Lazy` one, which is used by overloads of `RefCount` that specify a `disconnectDelay`, which disconnects only when the subscriber count has been at 0 for the duration specified. Both implementations had bugs.
Broadly speaking, the problems were failures to distinguish between different states when hitting significant subscriber counts.
The `Eager` implementation would crash if `minObservers` was greater than 1, and the subscriber count dropped below that threshold (but not to 0) and then back up to it. Each time `minObservers` was reached, it would reconnect, even if already connected. …
=> Fix RefCount bugs

Rx.NET/Integration/LinuxTests/LinuxTests.csproj, Rx.NET/Integration/WindowsDesktopTests/WindowsDesktopTests.csproj
Missed this when updating `version.json`
=> Update Rx PackageReferences to 6.1.0 in integration test

.editorconfig
The prevailing style for namespaces is the old block namespace. At some point I'd like to change that, but for now, the `.editorconfig` should reflect the repo style.
=> Add namespace style config to .editorconfig
